### ISSUE TITLE
SearchGUI should not assume a HOME direcory

### ISSUE THREAD

**Issue by bgruening** [compomics/searchgui#107]
On HPC environments you usually don't have a $HOME directory, but SearchGUI seems to need such a directory and want's to write into it. This causes the following problem. It would be nice if we can overwrite this behavior or if we can catch this error and issue a warning.

```
Fatal error: Java Exception
Picked up _JAVA_OPTIONS: -XX:MaxPermSize=2G -Xmx6G -Xms1G -Djava.io.tmpdir=/data/2/galaxy_db/tmp
An error occurred while saving /usr/local/galaxy/.compomics/userpreferences.cup (see below).
java.io.FileNotFoundException: /usr/local/galaxy/.compomics/userpreferences.cup (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at com.compomics.util.preferences.UtilitiesUserPreferences.saveUserPreferences(UtilitiesUserPreferences.java:626)
	at com.compomics.util.preferences.UtilitiesUserPreferences.loadUserPreferences(UtilitiesUserPreferences.java:645)
	at eu.isas.searchgui.cmd.FastaCLIInputBean.<init>(FastaCLIInputBean.java:44)
	at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:52)
	at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:175)
An error occurred while saving /usr/local/galaxy/.compomics/userpreferences.cup (see below).
java.io.FileNotFoundException: /usr/local/galaxy/.compomics/userpreferences.cup (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at com.compomics.util.preferences.UtilitiesUserPreferences.saveUserPreferences(UtilitiesUserPreferences.java:626)
	at com.compomics.util.preferences.UtilitiesUserPreferences.loadUserPreferences(UtilitiesUserPreferences.java:645)
	at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:74)
	at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:53)
	at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:175)
An error occurred while saving /usr/local/galaxy/.compomics/userpreferences.cup (see below).
java.io.FileNotFoundException: /usr/local/galaxy/.compomics/userpreferences.cup (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at com.compomics.util.preferences.UtilitiesUserPreferences.saveUserPreferences(UtilitiesUserPreferences.java:626)
	at com.compomics.util.preferences.UtilitiesUserPreferences.loadUserPreferences(UtilitiesUserPreferences.java:645)
	at eu.isas.searchgui.cmd.FastaCLI.generateTargetDecoyDatabase(FastaCLI.java:126)
	at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:76)
	at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:53)
	at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:175)
```

**Comment by mvaudel** [comment]
Hi Björn!

Are you using the `-temp_folder` and `-log` options? The first allows you to set the directory where temporary files are saved (home by default), the second should redirect the log to a file. More details on the [CLI documentation](https://github.com/compomics/searchgui/wiki/SearchCLI).

Hope this helps!

Marc

**Comment by bgruening** [comment]
Hi Marc,

we are using `-temp_folder` but not `-log`, this seems to be new. I will play around with it. Thanks!
While you are here ;) One more question: Which file from peptideshaker can I feed into moFF (on CLI)? Is this already supported. I haven't see it so far.
On the bright side: moFF is now running in Galaxy with dependencies. I just need to combine PS with moFF :)

Thanks,
Bjoern

**Comment by hbarsnes** [comment]
Hi Bjoern,

> Which file from peptideshaker can I feed into moFF (on CLI)? Is this already supported. I haven't see it so far.

From what I can see from the [moFF Github pages](https://github.com/compomics/moFF#input-data) the PeptideShaker input option seems to only be supported via the GUI. But I could be wrong. I'd recommend setting up a separate issue on the moFF issue tracker?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Bjoern,

> we are using  -temp_folder  but not  -log , this seems to be new. I will play around with it.

You sure you're using [PathSettingsCLI](https://github.com/compomics/searchgui/wiki/SearchCLI#pathsettingscli) to set the temp folder? As all the errors in your stack trace refer to the user preferences and not the log file.

Best regards,
Harald

**Comment by bgruening** [comment]
HI Harald,

currently we are using the SearchCLI to set the temp folder: https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/peptideshaker/searchgui.xml#L289

I will open a separate issue on moFF.
Thanks,
Bjoern

**Comment by hbarsnes** [comment]
Hi Bjoern,

> currently we are using the SearchCLI to set the temp folder: https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/peptideshaker/searchgui.xml#L289

Ok, but you're not using this option until after trying to use FastaCLI which also references the temp folders. So I'd recommend using the PathSettingsCLI separately first to set the temp folders, and then move on to use FastaCLI and SearchCLI. This should fix the problem.

Best regards,
Harald

**Comment by mvaudel** [comment]
Hi again,

I might be wrong but in https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/peptideshaker/searchgui.xml#L289 it does not seem that you are using the temp_folder for FastaCLI. Adding it there should also do the trick, but the solution of Harald is more elegant :)

Marc

**Comment by hbarsnes** [comment]
> I might be wrong but in https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/peptideshaker/searchgui.xml#L289 it does not seem that you are using the temp_folder for FastaCLI. Adding it there should also do the trick, but the solution of Harald is more elegant

As far as I can see FastaCLI does not support the temp_folder option (or indeed any of the path settings)? So my solution is not only more elegant, it is also the only solution that works. ;)

Harald

**Comment by bgruening** [comment]
This Java CLI stuff seems to be complicated ;) I will in-cooperate your suggestions in the next version of PS/SG versions. Thanks a lot!

**Comment by mvaudel** [comment]
> As far as I can see FastaCLI does not support the temp_folder option (or indeed any of the path settings)?

Good point, [now added](https://github.com/compomics/searchgui/commit/902dee81ebf1dda2ceacd5593b70ab2d1110fbee). Thanks @bgruening for the pointer!
