### ISSUE TITLE
peptideshaker bug

### ISSUE THREAD

**Issue by jflucier** [compomics/searchgui#111]
Hello again,

i am currently upgrading my installation of searchgui and peptideshaker installation to the latest version on CentOS6. I am stuck with a bug with latest version of peptideshaker (1.11). When I execute peptideshaker, I get this error message:

Thu Jun 30 13:30:38 EDT 2016 Importing sequences from searchgui_db_concatenated_target_decoy.fasta.
 0%
10% 20% 30% 40% 50%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Thu Jun 30 13:31:47 EDT 2016 An error occurred while loading the identification files:
Thu Jun 30 13:31:47 EDT 2016 820140
java.lang.ArrayIndexOutOfBoundsException: 820140
	at com.compomics.util.experiment.identification.protein_inference.fm_index.Rank.getRank(Rank.java:83)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:327)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:330)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRank(WaveletTree.java:305)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.createLessTable(WaveletTree.java:289)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:669)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1383)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1317)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:213)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:450)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:157)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:695)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:204)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:907)
Free memory: 7928043856
Thu Jun 30 13:31:47 EDT 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

My database has 466 606 entries. Can you guide me on how to resolve this bug. 

tks again for your help,

JF

**Comment by jflucier** [comment]
oups... sorry searchgui thread. Will repost in peptideshaker project. Sorry

**Comment by mvaudel** [comment]
No worries :) We are looking into the PeptideShaker one. In the meantime, can you try to add `-sequence_index_type 1` to your command line?

Apologies for the inconvenience,

Marc
