### ISSUE TITLE
NCBI nr.fasta decoy error

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/searchgui#121]
Hi, when trying to create a decoy database using all non-redundant sequences from NDBI (nr.fasta), I get this error, which then does not allow me to run the search:

[curanga@omica SearchGUI-3.1.1]$ java -cp SearchGUI-3.1.2.jar eu.isas.searchgui.cmd.FastaCLI -in "nr.fasta" -decoy "nr.fasta"
Input: /LUSTRE/curanga/proteomica/SearchGUI-3.1.1/nr.fasta

Name: nr
Version: 17.10.2016
Decoy Tag: null
Type: Generic_Header
Last modified: Mon Oct 17 07:34:47 PDT 2016
Size: 1523 sequences

Thu Oct 20 14:23:01 PDT 2016 Appending Decoy Sequences. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%Reindexing: nr_concatenated_target_decoy.fasta.
An error occurred while appending decoy sequences
java.lang.IllegalArgumentException: An error occurred while parsing the sequence of  at line 25: java.lang.IllegalArgumentException: No amino acid found for letter _.
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.createFastaIndex(SequenceFactory.java:775)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:703)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:633)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:574)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.appendDecoySequences(SequenceFactory.java:1129)
        at eu.isas.searchgui.cmd.FastaCLI.generateTargetDecoyDatabase(FastaCLI.java:175)
        at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:119)
        at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:59)
        at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:218)

**Comment by hbarsnes** [comment]
Hi,

Can you send us the FASTA file you are trying to use? Seems to be something strange with the sequences if they contain "_"?

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Well, it is a ~58 G file, so I am not quite sure how to send it to you. I don't have access to a fancy data repository. Perhaps you may know of a better way of downloading the NCBI nr database?

**Comment by hbarsnes** [comment]
Hi,

Could you try generating a smaller similar file and see if you still get the same problem? As the error occurs already on line 25 in your gigantic FASTA file.

Note that using a 58 GB database file will most likely break many of the search engines, or at the least it will take a very long time to run the searches. I would therefore try to look into reducing the size of the database as much as possible.

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Done, and it is now working. I created an NCBI database with target species
only. Thank you! I hope I don't break the computer with my learning
process 😅.

Best wishes,

Carla U.
