### ISSUE TITLE
Empty map when estimating the peptide PEP in PetideShaker

### ISSUE THREAD

**Issue by skiniry** [compomics/searchgui#139]
Hi, Not sure if this is an error with peptideshaker or searchgui but the log said to contact searchgui devs.So the problem is that I try to run a project with 24 mgf files this seems to process fine until the last step where it opens peptideshaker, then I get the following error:

_Wed Feb 15 21:42:03 GMT 2017        Zipping output files.

Wed Feb 15 21:59:24 GMT 2017        Processing identification files with PeptideShaker.

Thu Feb 16 02:34:02 GMT 2017        PeptideShaker processing failed. See the PeptideShaker log for details

Thu Feb 16 02:34:03 GMT 2017        Search Canceled!
Thu Feb 16 02:34:03 GMT 2017        Error: Stream closed
Thu Feb 16 02:34:03 GMT 2017        An error occurred while running SearchGUI. Please contact the developers.
Thu Feb 16 02:34:03 GMT 2017        The search or processing did not finish properly!_

If I try to open the searchgui_out.zip file in peptideshaker I get the following error: No peptideshaker project was found in the zip file.

Here is the peptideshaker log:

_Tue Feb 14 10:07:24 GMT 2017: PeptideShaker version 1.15.1.

Tue Feb 14 10:28:57 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 15270936576.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 150415680.
Java version: 1.7.0_79.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoyMap.estimateProbabilities(TargetDecoyMap.java:275)
	at eu.isas.peptideshaker.scoring.maps.PeptideSpecificMap.estimateProbabilities(PeptideSpecificMap.java:74)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:428)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:549)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:731)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:219)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:931)
Free memory: 1572241096

Tue Feb 14 16:44:04 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 15270936576.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 87291536.
Java version: 1.7.0_79.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_79
os.name: Linux
memory: 66.5/164.1
processors available: 24
useCommandThread: false

Wed Feb 15 10:07:58 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 15270936576.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 149755744.
Java version: 1.7.0_79.

Wed Feb 15 10:08:41 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 15270936576.
Total amount of memory in the Java virtual machine: 129499136.
Free memory: 83834992.
Java version: 1.7.0_79.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_79
os.name: Linux
memory: 66.6/164.1
processors available: 24
useCommandThread: false

Wed Feb 15 10:29:32 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 15270936576.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 149746808.
Java version: 1.7.0_79.

Wed Feb 15 10:30:11 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 15270936576.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 87314200.
Java version: 1.7.0_79.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_79
os.name: Linux
memory: 66.5/164.1
processors available: 24
useCommandThread: false
java.io.OptionalDataException
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1370)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1179)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1897)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1897)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1897)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1897)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1897)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at com.compomics.util.io.SerializationUtils.readObject(SerializationUtils.java:58)
	at com.compomics.util.experiment.io.ExperimentIO.loadExperiment(ExperimentIO.java:44)
	at eu.isas.peptideshaker.fileimport.CpsFileImporter.<init>(CpsFileImporter.java:57)
	at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:205)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:5447)

Wed Feb 15 21:59:29 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 30541873152.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 146919616.
Java version: 1.7.0_79.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoyMap.estimateProbabilities(TargetDecoyMap.java:275)
	at eu.isas.peptideshaker.scoring.maps.PeptideSpecificMap.estimateProbabilities(PeptideSpecificMap.java:74)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:428)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:549)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:731)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:219)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:931)
Free memory: 9829218816

Thu Feb 16 10:45:22 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 30541873152.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 125594176.
Java version: 1.7.0_79.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_79
os.name: Linux
memory: 46.5/164.1
processors available: 24
useCommandThread: false

Thu Feb 16 11:04:12 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 30541873152.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 125610536.
Java version: 1.7.0_79.

Thu Feb 16 11:36:22 GMT 2017: PeptideShaker version 1.15.1.
Memory given to the Java virtual machine: 30541873152.
Total amount of memory in the Java virtual machine: 164102144.
Free memory: 126245624.
Java version: 1.7.0_79.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_79
os.name: Linux
memory: 47.8/233.3
processors available: 24
useCommandThread: false_

**Comment by mvaudel** [comment]
Hi,

Thank you for reporting this issue. Would it be possible for you to import the SearchGUI file in the newest version of PeptideShaker? We have improved the part of the code that seems to be creating the problem. 

If the error persists, would it be possible for you to share the SearchGUI output, mgf, and fasta files with us?

Many thanks,

Marc

**Comment by skiniry** [comment]
So I've tried opening the output in peptideshaker 1.16.0 but get the same error. I have about 5gb of mgf files whats the best way to send them to you?

**Comment by mvaudel** [comment]
Hi again,

The best is to create a .tar.gz archive, put it on google drive, and share the access with me via email.

Best regards,

Marc

**Comment by mvaudel** [comment]
Hi again,

I just noticed that your database does not contain any decoys, is there any reason for this? Please note that PeptideShaker heavily relies on decoys to select the best hit per spectrum, calibrate its scores, and help you validate your results. When selecting your protein sequence database, SearchGUI should automatically propose to add decoys if you want to do so.

This might be why the tool is having problems, it should not crash, though. I will correct this and come back to you.

Apologies for the inconvenience,

Marc

**Comment by skiniry** [comment]
So I managed to get this to complete successfully but only by increasing the memory allocated to peptideshaker to 64gb. However there are other much larger PRIDE accessions (in terms of total file size) that I would like to run, but don't think I'll have enough memory. Would it be acceptable to split these into batches of files, or would this affect the peptideshakers scores?

**Comment by hbarsnes** [comment]
Hi,

I was just going over old issues and noticed that this one had not been replied to. So sorry for the very late reply!

> Would it be acceptable to split these into batches of files, or would this affect the peptideshakers scores?

You can split the spectrum files given that PeptideShaker process all the files at once. The splitting can however have a (most likely) minor impact on the search engine scores. We haven't done any in-depth testing to compare though.

And again, sorry for the very late reply!

Best regards,
Harald

PS: I'm now closing this issue, but please don't hesitate to open a new one if you experience other problems with our software.
