### ISSUE TITLE
N-terminal Cofradic data processing

### ISSUE THREAD

**Issue by vladie0** [compomics/searchgui#163]
Dear SearchGUI developers,

We're experiencing issues trying to process our data using your tools. The data we're attempting to process is publicly available on PRIDE (https://www.ebi.ac.uk/pride/archive/projects/PXD005579). The protocol stated in the study requires the addition of some unique modification, a brief description of the modifications can be found here:

Heavy acetylation at lysine side-chains (Acetyl:2H(3)C13(2) (K)), carbamidomethylation of cysteine and methionine oxidation to methionine-sulfoxide were set as fixed modifications. Variable modifications were formylation, acetylation and heavy acetylation of N-termini (Acetyl:2H(3)C13(2) (N-term)) and pyroglutamate formation of N-terminal glutamine (both at peptide level). Endoproteinase semi-Arg-C/P (semi Arg-C specificity with Arg-Pro cleavage allowed) was set as enzyme allowing for no missed cleavages.

Some of these modifications were not present in your tool and have been added manually. The first issues we experienced is that some search engines were unable to process the data, presumably due to the modification (for example X! tandem). For MS GF+ and OMSSA, SearchGUI was able process the data successfully, However, errors occured when processing the data in PeptideShaker. I assume that this issue is caused by the unique parameter setting needed by the study.

The error and log can be found below:
PeptideShaker ERROR:
Thu Mar 01 18:32:40 CET 2018 Computing peptide probabilities.
Thu Mar 01 18:32:40 CET 2018 Estimating Probabilities. Please Wait...
10% 20%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Thu Mar 01 18:32:40 CET 2018 An error occurred while loading the identification files:
Thu Mar 01 18:32:40 CET 2018 Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoyMap.estimateProbabilities(TargetDecoyMap.java:275)
        at eu.isas.peptideshaker.scoring.maps.PeptideSpecificMap.estimateProbabilities(PeptideSpecificMap.java:74)
        at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:428)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:547)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:735)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:935)
Free memory: 12286625192

Last Log lines:
java.sql.SQLException: The conglomerate (384) requested does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
        at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at com.compomics.util.db.ObjectsDB.updateObjectInDb(ObjectsDB.java:1350)
        at com.compomics.util.db.ObjectsDB.updateObject(ObjectsDB.java:1315)
        at com.compomics.util.db.ObjectsDB.saveAttributes(ObjectsDB.java:1431)
        at com.compomics.util.db.ObjectsDB.close(ObjectsDB.java:1483)
        at com.compomics.util.experiment.identification.IdentificationDB.close(IdentificationDB.java:1421)
        at com.compomics.util.experiment.identification.Identification.close(Identification.java:1643)
        at eu.isas.peptideshaker.gui.PeptideShakerGUI.clearDatabaseFolder(PeptideShakerGUI.java:4220)
        at eu.isas.peptideshaker.gui.PeptideShakerGUI.clearData(PeptideShakerGUI.java:4188)
        at eu.isas.peptideshaker.gui.PeptideShakerGUI$92.run(PeptideShakerGUI.java:4765)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.sql.SQLException: The conglomerate (384) requested does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 49 more
Caused by: ERROR XSAI2: The conglomerate (384) requested does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.store.access.heap.HeapConglomerateFactory.readConglomerate(Unknown Source)
        at org.apache.derby.impl.store.access.CacheableConglomerate.setIdentity(Unknown Source)
        at org.apache.derby.impl.services.cache.ConcurrentCache.find(Unknown Source)
        at org.apache.derby.impl.store.access.RAMAccessManager.conglomCacheFind(Unknown Source)
        at org.apache.derby.impl.store.access.RAMTransaction.findConglomerate(Unknown Source)
        at org.apache.derby.impl.store.access.RAMTransaction.findExistingConglomerate(Unknown Source)
        at org.apache.derby.impl.store.access.RAMTransaction.openConglomerate(Unknown Source)
        at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.getDescriptorViaIndexMinion(Unknown Source)
        at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.getDescriptorViaIndex(Unknown Source)
        at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.getAliasDescriptor(Unknown Source)
        at org.apache.derby.impl.sql.compile.QueryTreeNode.resolveTableToSynonym(Unknown Source)
        at org.apache.derby.impl.sql.compile.UpdateNode.bindStatement(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
        ... 43 more
                    
I have uploaded the complete SearchGUI zip (with mgf & parameter files) processed with MS GF+ and OMSSA, which can be found here:

https://www.dropbox.com/s/os37r98csf7iok5/searchgui_out.zip?dl=0

Which search engines do you advise to use for this project?
Is there a way to make X! Tandem work with our settings (We favor the use of this search engine).
Is there a way to solve PeptideShaker issues with the resulting SearchGUI output ? 

Thank you in advance,
Volodimir Olexiouk

**Comment by hbarsnes** [comment]
Hi Volodimir,

The issue with processing the data in PeptideShaker will hopefully be solved in the next release. At this time we're not sure when it'll become available though.

As for the issues with X!Tandem, the problem seems to be the addition of the "Heavy Acetylation peptide N-termini" modification in combination with the other modifications, because if I remove this one it works. (I also had to change the enzyme to "Arg-C (no P-rule)", as it was set to "Whole Protein" in the parameter file you sent to me btw.)

We've started looking into how to support your modification settings for X!Tandem in the next release, but came across some related issues that have to be resolved first. @mvaudel will get back to you once we have a new version for you to test.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Volodimir,

Just a quick update on the X! Tandem issue with regards to the modification settings. I've just tested the upcoming release of SearchGUI and there X! Tandem works fine with the given set of modifications. I'll let you know when the new version becomes available.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Volodimir,

This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker.
Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved with the release of the new versions. If this is not the case, please let us know and we'll reopen the issue.
