### ISSUE TITLE
semi-specific not supported

### ISSUE THREAD

**Issue by vladie0** [compomics/searchgui#169]
Dear developers, 

In an attempt to change the database of a parameter file through the command line interface I encounter the following error:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/data2/vladie/petra/SearchGUI-3.2.24/lib/gson-2.4.jar) to field java.awt.Color.value
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.UnsupportedOperationException: Specificity Semi-Specific not supported.
        at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:2333)
        at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:1663)
        at com.compomics.cli.identification_parameters.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:79)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)

This does not happen with previous versions (version used: 3.2.24)

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. There seems to be a missing break statement. We'll fix the problem and release a new version by the end of the week.

Best regards, 
Harald

**Comment by vladie0** [comment]
Thank you,
Also, after adjust the parameter files though the GUI, I've tried to process the files using searchGUI.

I'm encoutering the following error:
                Commencing first-stage searchGUI search against /data2/vladie/petra/PXD005579/SALT_Sl1344_6FT_allNRO_annot_concatenated_target_decoy.fasta
java.lang.UnsupportedOperationException: Specificity Semi-Specific not supported.
        at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:2333)
        at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:1663)
        at eu.isas.searchgui.cmd.SearchCLIInputBean.<init>(SearchCLIInputBean.java:365)
        at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:91)
        at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:403)

**Comment by hbarsnes** [comment]
Hi again,

This is exactly the same error and due to the same missing break statement. Both will be fixed in the next release.

Best regards, 
Harald

**Comment by hbarsnes** [comment]
Hi Volodimir,

We've just released new versions of both SearchGUI and PeptideShaker that should fix this problem. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
