### ISSUE TITLE
MS Amanda error in SearchGUI-3.2.24

### ISSUE THREAD

**Issue by chrishuges** [compomics/searchgui#170]
Running a standard search in the latest SearchGUI using the CLI version on a linux machine. Get the error:

Cannot run program "mono" (in directory "/projects/ptx_analysis/chughes/software/searchGUI_apr2018/SearchGUI-3.2.24/resources/MS Amanda/linux"): error=2, No such file or directory
java.io.IOException: Cannot run program "mono" (in directory "/projects/ptx_analysis/chughes/software/searchGUI_apr2018/SearchGUI-3.2.24/resources/MS Amanda/linux"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at eu.isas.searchgui.processbuilders.SearchGUIProcessBuilder.startProcess(SearchGUIProcessBuilder.java:77)
        at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2050)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at javax.swing.SwingWorker.run(SwingWorker.java:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 8 more

Seems it does not like the space in the MS Amanda file path.

**Comment by hbarsnes** [comment]
Hi Christopher,

That is strange. You sure you have mono installed? Can you try running the MS Amanda command line directly from the terminal? 

Best regards, 
Harald

**Comment by chrishuges** [comment]
Yup it was a Mono error. Working correctly now. Thanks!
