### ISSUE TITLE
MS-GF error after upgrade to 3.3.1

### ISSUE THREAD

**Issue by chrishuges** [compomics/searchgui#175]
Using SearchCLI in version 3.3.1, executing an MS-GF+ search I get the error:

ms-gf+ command: 
/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.91.x86_64/jre/bin/java -Xmx300g -jar /projects/ptx_analysis/chughes/software/searchGUI_may2018/resources/MS-GF+/MSGFPlus.jar -s /projects/ptx_results/OtherDataSets/2017-Feb_McApline-Endo/mgf/ch_08Feb2017_Endo-McAlpine_TMT10_hph_a_10_MGF.mgf -d /projects/ptx_analysis/chughes/databases/current/uniprot_human-crap_may2018_FWD_concatenated_target_decoy.fasta -o /projects/ptx_results/OtherDataSets/2017-Feb_McApline-Endo/search-output/.SearchGUI_temp/ch_08Feb2017_Endo-McAlpine_TMT10_hph_a_10_MGF.msgf.mzid -t 20.0ppm -tda 0 -mod /projects/ptx_analysis/chughes/software/searchGUI_may2018/resources/MS-GF+/params/Mods.txt -minCharge 2 -maxCharge 4 -inst 0 -thread 144 -m 0 -e 1 -ntt 2 -protocol 4 -minLength 8 -maxLength 30 -n 10 -addFeatures 0 -ti 0,1 

Thu May 10 18:50:21 PDT 2018 Processing ch_08Feb2017_Endo-McAlpine_TMT10_hph_a_10_MGF.mgf with MS-GF+.

Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/ebi/jmzidml/model/mzidml/AbstractParam : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at edu.ucsd.msjava.msutil.ActivationMethod.<init>(ActivationMethod.java:29)
        at edu.ucsd.msjava.msutil.ActivationMethod.<clinit>(ActivationMethod.java:131)
        at edu.ucsd.msjava.params.ParamManager.addMSGFPlusParams(ParamManager.java:308)
        at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:34)

Thought it might be a java error:

bash-4.1$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

Do I need to upgrade Java for MS-GF+ to work with the new SearchCLI?

Thanks!
Chris

**Comment by chrishuges** [comment]
Just to add, I tried it on a different machine with newer java:

java version "1.7.0_151"
OpenJDK Runtime Environment (rhel-2.6.11.1.el7_4-x86_64 u151-b00)
OpenJDK 64-Bit Server VM (build 24.151-b00, mixed mode)

I get the same error.

**Comment by hbarsnes** [comment]
Hi Chris,

It seems like the new MS-GF+ version requires Java 8. At least that is what I have on my laptop and there it runs fine. I will check with the MS-GF+ developer whether it really requires Java 8 or if they can lower the requirement to Java 7.

In any case, if you update to Java 8 (which is recommended anyway), I think the new MS-GF+ should work. Let me know if this solves the problem.

Best regards,
Harald

**Comment by hbarsnes** [comment]
You can follow the reply from the MS-GF+ developers here: https://github.com/MSGFPlus/msgfplus/issues/31

**Comment by chrishuges** [comment]
Updated to Java 8, and MS-GF+ works fine in SearchCLI 3.3.1 now. Thanks!
