### ISSUE TITLE
IdentificationParametersCLI exception

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/searchgui#192]
Got another problem with the Galaxy wrapper. For the step

```
searchgui -Djava.awt.headless=true eu.isas.searchgui.cmd.IdentificationParametersCLI --exec_dir="$cwd/bin" -out SEARCHGUI_IdentificationParameters.par   -frag_tol '0.02' -frag_ppm '0' -prec_tol '5.0' -prec_ppm '1'  -min_charge 2 -max_charge 6 -fi b -ri y -min_isotope 0 -max_isotope 1 -enzyme "Trypsin" -mc "2"  -fixed_mods "Carbamidomethylation of C"    -db input_database.fasta -useGeneMapping 0 -updateGeneMapping 0   -xtandem_npeaks 50 -xtandem_min_peaks 15 -xtandem_min_frag_mz 200 -xtandem_min_prec_mass 200 -xtandem_noise_suppr 1 -xtandem_dynamic_range 100 -xtandem_quick_acetyl 1 -xtandem_quick_pyro 1 -xtandem_stp_bias 0 -xtandem_evalue 0.01 -xtandem_output_proteins 0 -xtandem_output_sequences 0 -xtandem_output_spectra 1    -msgf_decoy 0 -msgf_min_pep_length 6 -msgf_max_pep_length 30 -msgf_termini 2 -msgf_num_ptms 2 -msgf_instrument 3 -msgf_fragmentation 3 -msgf_protocol 0 -msgf_num_matches 1 -msgf_additional 0
```

I get:

```
java.lang.NumberFormatException: For input string: "<html><head>"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.<init>(Integer.java:867)
	at com.compomics.util.experiment.biology.taxonomy.mappings.UniprotTaxonomy.downloadMapping(UniprotTaxonomy.java:138)
	at com.compomics.util.experiment.biology.taxonomy.mappings.UniprotTaxonomy.getId(UniprotTaxonomy.java:187)
	at com.compomics.util.preferences.GenePreferences.setPreferencesFromSearchParameters(GenePreferences.java:154)
	at com.compomics.util.preferences.IdentificationParameters.setParametersFromSearch(IdentificationParameters.java:550)
	at com.compomics.util.preferences.IdentificationParameters.<init>(IdentificationParameters.java:101)
	at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:3073)
	at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:1669)
	at com.compomics.cli.identification_parameters.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:79)
	at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
	at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)
```

I tried to reproduce this manually. The odd thing is that the error occurs only every second execution.

**Comment by hbarsnes** [comment]
That's strange. Never seen that kind of error before. Would it be possible for you to send me the FASTA file?

But in any case, I guess maybe this information should not even be attempted dowloaded when using "-useGeneMapping 0 -updateGeneMapping 0". Will look into that part and get back to you.

Odd that it only happens every second time though. And that is with identical input I assume?

**Comment by bernt-matthias** [comment]
Just for completeness the complete command line that is executed: 

```
mkdir output; 
mkdir output_reports; 
cwd=`pwd`; 
export HOME=$cwd;  
echo "" > searchgui_stderr &&  
echo 'X!Tandem,MSGF'; 
echo 'DB: 170508_SIHUMI_n8_species.fasta sequences: 29557';  
echo 'searchgui.version=3.3.5' >> searchgui.properties;  
ln -s -f '/gpfs1/data/galaxy_server/galaxy/database/files/046/dataset_46598.dat' '17-09-2018_Gelfree_F6-8_inSolution_HP.mgf'; 
echo 'Spectrums:17-09-2018_Gelfree_F6-8_inSolution_HP.mgf(API:9cd8582696084118)'; 
ln -s -f '/gpfs1/data/galaxy_server/galaxy/database/files/046/dataset_46596.dat' '17-09-2018_Gelfree_F1-5_inSolution_HP.mgf'; 
echo 'Spectrums:17-09-2018_Gelfree_F1-5_inSolution_HP.mgf(API:d52a149b60b3592b)'; 
cp "/gpfs1/data/galaxy_server/galaxy/database/files/046/dataset_46602.dat" input_database.fasta;  echo 'Setting paths' && 

searchgui -Djava.awt.headless=true eu.isas.searchgui.cmd.PathSettingsCLI --exec_dir="$cwd/bin" -temp_folder $cwd -log $cwd/searchgui.log  2>> searchgui_stderr &&  echo 'Creatin
 g decoy database.' && 

searchgui -Djava.awt.headless=true eu.isas.searchgui.cmd.FastaCLI --exec_dir="$cwd/bin" -in input_database.fasta -decoy  2>> searchgui_stderr && rm input_database.fasta && cp input_database_concatenated_target_decoy.fasta input_database.fasta &&  echo 'setting identification parameters' && 

(searchgui -Djava.awt.headless=true eu.isas.searchgui.cmd.IdentificationParametersCLI --exec_dir="$cwd/bin" -out SEARCHGUI_IdentificationParameters.par   -frag_tol '0.02' -frag_ppm '0' -prec_tol '5.0' -prec_ppm '1'  -min_charge 2 -max_charge 6 -fi b -ri y -min_isotope 0 -max_isotope 1 -enzyme "Trypsin" -mc "2"  -fixed_mods "Carbamidomethylation of C"    -db input_database.fasta -useGeneMapping 0 -updateGeneMapping 0   -xtandem_npeaks 50 -xtandem_min_peaks 15 -xtandem_min_frag_mz 200 -xtandem_min_prec_mass 200 -xtandem_noise_suppr 1 -xtandem_dynamic_range 100 -xtandem_quick_acetyl 1 -xtandem_quick_pyro 1 -xtandem_stp_bias 0
  -xtandem_evalue 0.01 -xtandem_output_proteins 0 -xtandem_output_sequences 0 -xtandem_output_spectra 1    -msgf_decoy 0 -msgf_min_pep_length 6 -msgf_max_pep_length 30 -msgf_termini 2 -msgf_num_ptms 2 -msgf_instrument 3 -msgf_fragmentation 3 -msgf_protocol 0 -msgf_num_matches 1 -msgf_additional 0           2> searchgui_stderr) &&  

(searchgui -Djava.awt.headless=true eu.isas.searchgui.cmd.SearchCLI --exec_dir="$cwd/bin" -spectrum_files $cwd -output_folder $cwd/output -id_params SEARCHGUI_IdentificationParameters.par  -threads "${GALAXY_SLOTS:-12}"  -correct_titles "1" -missing_titles 0 -mgf_splitting "1000" -mgf_spectrum_count "25000"    -xtandem 1  -myrimatch 0  -msgf 1  -omssa 0  -comet 0  -tide 0  -ms_amanda 0  -andromeda 0  -novor 0  -directag 0  -output_option 0  -output_data 1  2>> searchgui_stderr)  &&  
```

**Comment by hbarsnes** [comment]
Found the reason for the exception being thrown. It was due to using http and not https when accessing UniProt. This has now been corrected and new versions released.

Still need to look into why UniProt is accessed in the first place though. As I think this ought not happen when the use of the gene mappings is set to off.

Also, I have no idea why it would fail every second time. Isn't this going against the concept of Galaxy where each run should be started from scratch with the same environment?

**Comment by bernt-matthias** [comment]
> Found the reason for the exception being thrown. It was due to using http and not https when accessing UniProt. This has now been corrected and new versions released. Still need to look into why UniProt is accessed in the first place though. As I think this ought not happen when the use of the gene mappings is set to off.

good news.

> Also, I have no idea why it would fail every second time. Isn't this going against the concept of Galaxy where each run should be started from scratch with the same environment?

That's right, galaxy would start from scratch. The additional calls were done manually by me in the working directory of the failed jobs.

**Comment by bernt-matthias** [comment]
> The odd thing is that the error occurs only every second execution.

I have to clarify this: It fails for the first call (i.e. from Galaxy on a clean working dir) and from then on it alternated between failing and working.

**Comment by hbarsnes** [comment]
New versions of both SearchGUI and PeptideShaker have now been released. This should fix both issues above. First that https is used when contacting UniProt (removing the html parsing error) and that UniProt is not contacted in the first place when using the command line with -useGeneMapping set to 0.

**Comment by bernt-matthias** [comment]
Cool. Thanks. I will prepare the upgrades to the conda packages and Galaxy tools 

* for PeptideShaker 1.16.31 to 1.16.35
* for SearchGUI 3.3.5 to 3.3.9 

Can you tell me if any command line options are affected by this upgade? If not I can just bump the Galaxy tool version.

**Comment by hbarsnes** [comment]
No changes to the command lines. Only some new default PTMs added. See the release notes for details.
