### ISSUE TITLE
Searchgui gives genemapping error on startup

### ISSUE THREAD

**Issue by hale94** [compomics/searchgui#224]
This is the log message.  All searches terminate early.

java.io.FileNotFoundException: C:\Users\John\.compomics\gene_mappings\ensembl_versions (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at com.compomics.util.experiment.biology.genes.GeneFactory.updateEnsemblVersion(GeneFactory.java:785)
	at com.compomics.util.experiment.biology.genes.GeneFactory.createDefaultGeneMappingFilesGeneric(GeneFactory.java:703)
	at com.compomics.util.experiment.biology.genes.GeneFactory.initialize(GeneFactory.java:118)
	at eu.isas.searchgui.gui.SearchGUI.<init>(SearchGUI.java:299)
	at eu.isas.searchgui.gui.SearchGUI.main(SearchGUI.java:5789)

**Comment by hbarsnes** [comment]
Hi,

The problem seems to be that you are not allowed to write to the temp folders used by SearchGUI (and PeptideShaker), hence the "Access is denied" message above.

You can easily fix this by changing the temp folders. In SearchGUI this is done via Edit > Resource Settings. (And in PeptideShaker via the Welcome dialog > Settings & Help > Settings > Resource Settings.)

Simply right-click in table and change the paths to folders where you have read and write access.

Best regards,
Harald

**Comment by hale94** [comment]
Harald,

 

That solved the gene maping error fpr searchgui but not peptideshaker.  I am having several other issues like not being able to import or save parameter files.  I loaded anaconda on my computer a couple of days ago.  Could that be creating conflicts with java?  If so, is there anything I can do to recover the programs?

 

Thanks,

 

John

**Comment by hbarsnes** [comment]
Hi John,

> That solved the gene maping error fpr searchgui but not peptideshaker.  I am having several other issues like not being able to import or save parameter files.  I loaded anaconda on my computer a couple of days ago.  Could that be creating conflicts with java?  If so, is there anything I can do to recover the programs?

Did you make sure to also update the temp paths for PeptideShaker?

Are there any errors in the PeptideShaker log file? You'll find it via the Welcome dialog > Settings & Help > Help > Bug Report.

Best regards,
Harald

**Comment by hale94** [comment]
Harald,  I did update all temp paths. What finally worked was I moved the .compomics folder out of my user folder onto my desktop.  All programs are working now.

 

Thanks,

 

John
