### ISSUE TITLE
SearchGUI Error: Map failed

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/searchgui#288]
I observe the following error when running SearchGUI from Galaxy (using the latest version available for Galaxy, i.e. 4.0.12)

```
Fri Mar 12 15:12:56 CET 2021 Importing spectrum files.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Fri Mar 12 15:57:07 CET 2021 Error: Map failed
Fri Mar 12 15:57:07 CET 2021 An error occurred while running SearchGUI. Please contact the developers.
Fri Mar 12 15:57:07 CET 2021 The search or processing did not finish properly!
```

Any advice what could be the source of such an error?

**Comment by hbarsnes** [comment]
Have you checked the content of the SearchGUI log file? There should be a stacktrace there?

**Comment by bernt-matthias** [comment]
@hbarsnes thanks for the reply. Here it is: ` cat log_folder/SearchGUI.log`: 

```
Sun Mar 14 16:30:41 CET 2021: SearchGUI version 4.0.12.
Memory given to the Java virtual machine: 6227755008.
Total amount of memory in the Java virtual machine: 259522560.
Free memory: 253791392.
Java version: 11.0.8-internal.
java.io.IOException: Map failed
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:1016)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileReader.<init>(CmsFileReader.java:141)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.register(MsFileHandler.java:153)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2547)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.OutOfMemoryError: Map failed
	at java.base/sun.nio.ch.FileChannelImpl.map0(Native Method)
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:1013)
	... 9 more
```

`cat log_folder/SearchGUI\ Report\ 2021-03-14\ 17.15.01.html`

```
<html># ------------------------------------------------------------------<br># General Search Parameters<br># ------------------------------------------------------------------<br><br>ENZYME0=Trypsin, Specific, 2 missed cleavages<br>FIXED_MODIFICATIONS=Acetylation of peptide N-term,Carbamidomethylation of C<br>VARIABLE_MODIFICATIONS=Oxidation of M<br>REFINEMENT_FIXED_MODIFICATIONS=<br>REFINEMENT_VARIABLE_MODIFICATIONS=<br>PRECURSOR_MASS_TOLERANCE=10.0<br>PRECURSOR_MASS_TOLERANCE_UNIT=ppm<br>FRAGMENT_MASS_TOLERANCE=0.05<br>FRAGMENT_MASS_TOLERANCE_UNIT=Da<br>PPM_TO_DA_CONVERSION_REF_MASS=2000.0<br>FORWARD_FRAGMENT_ION_TYPE=b<br>FRAGMENT_ION_TYPE_2=y<br>PRECURSOR_CHARGE_LOWER_BOUND=2<br>PRECURSOR_CHARGE_UPPER_BOUND=4<br>ISOTOPIC_CORRECTION_LOWER_BOUND=0<br>ISOTOPIC_CORRECTION_UPPER_BOUND=1<br><br><br># ------------------------------------------------------------------<br># OMSSA Specific Parameters<br># ------------------------------------------------------------------<br><br>EVALUE_CUTOFF=100.0<br>MAXIMUM_HITLIST_LENGTH=10<br>PRECURSOR_ELIMINATION=false<br>PRECURSOR_SCALING=true<br>MINIMAL_PEPTIDE_SIZE=8<br>MAXIMAL_PEPTIDE_SIZE=30<br>PRECURSOR_CHARGE_TO_CONSIDER_MULTIPLY_CHARGED_FRAGMENTS=3<br>CHARGE_ESTIMATION=true<br>OUTPUT_TYPE=OMX<br>MEMORY_MAPPED_SEQUENCES=false<br>MASS_TO_CONSIDER_EXACT_NEUTRON_MASS=1446.94<br>LOW_INTENSITY_CUTOFF=0.0<br>HIGH_INTENSITY_CUTOFF=0.2<br>INTENSITY_INCREMENT=5.0E-4<br>SINGLE_CHARGE_WINDOW_WIDTH=27<br>DOUBLE_CHARGE_WINDOW_WIDTH=14<br>SINGLE_CHARGE_WINDOW_NPEAKS=2<br>DOUBLE_CHARGE_WINDOW_NPEAKS=2<br>MAX_HITS_PER_SPECTRUM_PER_CHARGE=30<br>MIN_ANNOTATED_INTENSE_PEAKS=6<br>MIN_ANNOTATED_PEAKS=2<br>MIN_PEAKS=4<br>CLEAVE_TERMINAL_METHIONINE=true<br>MAX_MZ_LADDERS=128<br>MAX_FRAGMENT_CHARGE=2<br>FRACTION_PEAKS_FOR_CHARGE_1_ESTIMATION=0.95<br>AUTO_DETERMINE_CHARGE_ONE=true<br>SEARCH_POSITIVE_IONS=true<br>MIN_PERCURSORS_PER_SPECTRUM=1<br>FORWARD_FRAGMENTS_FIRST=false<br>REWIND_FRAGMENTS=true<br>FRAGMENTS_PER_SERIES=100<br>CORRELATION_CORRECTION_SCORE=true<br>CONSECUTIVE_ION_PROBABILITY=0.5<br>ITERATIVE_SEARCH_SEQUENCE_EVALUE=0.0<br>ITERATIVE_SEARCH_SPECTRUM_EVALUE=0.01<br>ITERATIVE_SEARCH_REPLACEMENT_EVALUE=0.0<br><br><br># ------------------------------------------------------------------<br># MetaMorpheus Specific Parameters<br># ------------------------------------------------------------------<br><br>MIN_PEPTIDE_LENGTH=8<br>MAX_PEPTIDE_LENGTH=30<br>SEARCH_TYPE=Classic<br>NUM_PARTITIONS=1<br>DISSOCIATION_TYPE=HCD<br>MAX_MODS_FOR_PEPTIDE=2<br>INITIATOR_METHIONINE_BEHAVIOR=Variable<br>SCORE_CUTOFF=5.0<br>USE_DELTA_SCORE=false<br>FRAGMENTATION_TERMINUS=Both<br>MAX_FRAGMENTATION_SIZE=30000.0<br>MASS_DIFF_ACCEPTOR_TYPE=OneMM<br>WRITE_MZID=true<br>WRITE_PEPXML=false<br>USE_PROVIDED_PRECURSOR=true<br>DO_PREC_DECONVOLUTION=true<br>DECONVOLUTION_INT_RATIO=3.0<br>DECONVOLUTION_MASS_TOL=4.0<br>DECONVOLUTION_MASS_TOL_TYPE=PPM<br>TRIM_MS1_PEAKS=false<br>TRIM_MSMS_PEAKS=true<br>NUM_PEAKS_PER_WINDOWS=200<br>MIN_ALLOWED_INT_RATIO_TO_BASE_PEAK=0.01<br>WINDOW_WITH_THOMPSON=null<br>NUM_WINDOWS=null<br>NORMALIZE_PEAKS_ACROSS_ALL_WINDOWS=false<br>MOD_PEPTIDES_ARE_DIFFERENT=false<br>NO_ONE_HIT_WONDERS=false<br>SEARCH_TARGET=true<br>DECOY_TYPE=None<br>MAX_MOD_ISOFORMS=1024<br>MIN_VARIANT_DEPTH=1<br>MAX_HETROZYGOUS_VARIANTS=4<br>RUN_GPTM=false<br>GPTMS=Common Biological, Common Artifact, Metal<br><br><br># ------------------------------------------------------------------<br># X!Tandem Specific Parameters<br># ------------------------------------------------------------------<br><br>DYNAMIC_RANGE=100.0<br>NUMBER_OF_PEAKS=50<br>MIN_FRAG_MASS=200.0<br>MIN_NUMBER_OF_PEAKS=5<br>NOISE_SUPPRESSION=NO<br>PARENT_MONOISOTOPIC_MASS_ISOTOPE_ERROR=YES<br>MIN_PREC_MASS=500.0<br>PROTEIN_QUICK_ACETYL=YES<br>QUICK_PYROLIDONE=YES<br>PROTEIN_PTM_COMPLEXITY=6.0<br>STP_BIAS=NO<br>REFINE=YES<br>REFINE_SEMI=NO<br>REFINE_POINT_MUTATIONS=NO<br>REFINE_SPECTRUM_SYNTHESIS=YES<br>REFINE_UNANTICIPATED_CLEABAGES=YES<br>REFINE_SNAPS=YES<br>REFINE_MAX_EVALUE=0.01<br>POTENTIAL_MODIFICATIONS_FOR_FULL_REFINEMENT=NO<br>EVALUE_CUTOFF=0.01<br>SKYLINE_PATH=<br>OUTPUT_RESULTS=all<br>OUTPUT_PROTEINS=YES<br>OUTPUT_SEQUENCES=NO<br>OUTPUT_SPECTRA=YES<br>OUTPUT_HISTOGRAMS=NO<br><br><br># ------------------------------------------------------------------<br># PepNovo+ Specific Parameters<br># ------------------------------------------------------------------<br><br>HIT_LIST_LENGTH=10<br>CORRECT_PRECURSOR_MASS=false<br>DISCARD_LOW_QUALITY_SPECTRA=true<br>FRAGMENTATION_MODEL=CID_IT_TRYP<br>GENERATE_QUERY=false<br><br><br># ------------------------------------------------------------------<br># Andromeda Specific Parameters<br># ------------------------------------------------------------------<br><br>MIN_PEPTIDE_LENGHT_NO_ENZYME=8<br>MAX_PEPTIDE_LENGHT_NO_ENZYME=30<br>MAX_PEPTIDE_MASS=4600.0<br>NUMBER_SPECTRUM_MATCHES=10<br>MAX_PTMS=5<br>FRAGMENTATION_METHOD=CID<br>WATER_LOSS=true<br>AMMONIA_LOSS=true<br>SEQUENCE_DEPENDENT_NEUTRAL_LOSS=true<br>EQUAL_IL=false<br>FRAGMENT_ALL=false<br>EMPERICAL_CORRECTION=true<br>HIGHER_CHARGE=true<br>MAX_COMBINATIONS=250<br>TOP_PEAKS=8<br>TOP_PEAKS_WINDOW=100<br>DECOY_MODE=none<br><br><br># ------------------------------------------------------------------<br># MS Amanda Specific Parameters<br># ------------------------------------------------------------------<br><br>SEARCH_DECOY=false<br>REPORT_BOTH_BEST_HITS_FOR_TD=true<br>INSTRUMENT_ID=b, y<br>MONOISOTOPIC=true<br>MAX_RANK=10<br>PERFORM_DEISOTOPING=true<br>MAX_MODIFICATIONS=3<br>MAX_VARIABLE_MODIFICATIONS=4<br>MAX_MODIFICATIONS_SITES=6<br>MAX_NEUTRAL_LOSSES=1<br>MAX_NEUTRAL_LOSSES_PER_MODIFICATION=2<br>MIN_PEPTIDE_LENGTH=8<br>MAX_PEPTIDE_LENGTH=30<br>MAX_LOADED_PROTEINS=100000<br>MAX_LOADED_SPECTRA=2000<br>OUTPUT_FORMAT=csv<br><br><br># ------------------------------------------------------------------<br># MS-GF+ Specific Parameters<br># ------------------------------------------------------------------<br><br>SEARCH_DECOY=false<br>INSTRUMENT_ID=3<br>FRAGMENTATION_ID=3<br>PROTOCOL_ID=0<br>MIN_PEP_LENGTH=8<br>MAX_PEP_LENGTH=30<br>NUMBER_SPECTRUM_MATCHES=10<br>ADDITIONAL_OUTPUT=false<br>NUMBER_OF_TOLERABLE_TERMINI=2<br>MAX_NUMBER_MODIFICATIONS=2<br>NUMBER_TASKS=null<br><br><br># ------------------------------------------------------------------<br># DirecTag Specific Parameters<br># ------------------------------------------------------------------<br><br>TIC_CUTOFF_PERCENTAGE=100.0<br>MAX_PEAK_COUNT=100<br>NUM_INTENSITY_CLASSES=3<br>ADJUST_PRECURSOR_MASS=false<br>MIN_PRECUSOR_ADJUSTMENT=-0.5<br>MAX_PRECUSOR_ADJUSTMENT=1.5<br>PRECUSOR_ADJUSTMENT_STEP=0.1<br>NUM_CHARGE_STATES=3<br>OUTPUT_SUFFIX=<br>USE_CHARGE_STATE_FROM_MS=true<br>DUPLICATE_SPECTRA=true<br>DEISOTOPING_MODE=0<br>ISOTOPE_MZ_TOLERANCE=0.25<br>COMPLEMENT_MZ_TOLERANCE=0.1<br>TAG_LENGTH=4<br>MAX_DYNAMIC_MODS=2<br>MAX_TAG_COUNT=10<br>INTENSITY_SCORE_WEIGHT=1.0<br>MZ_FIDELITY_SCORE_WEIGHT=1.0<br>COMPLEMENT_SCORE_WEIGHT=1.0<br><br><br># ------------------------------------------------------------------<br># Comet Specific Parameters<br># ------------------------------------------------------------------<br><br>NUMBER_SPECTRUM_MATCHES=10<br>MAX_VARIABLE_MODS=10<br>REQUIRE_VARIABLE_MODS=false<br>MIN_PEAKS=10<br>MIN_PEAKS_INTENSITY=0.0<br>REMOVE_PRECURSOR=0<br>REMOVE_PRECURSOR_TOLERANCE=1.5<br>LOWER_CLEAR_MZ_RANGE=0.0<br>UPPER_CLEAR_MZ_RANGE=0.0<br>ENZYME_TYPE=2<br>ISOTOPE_CORRECTION=3<br>MIN_PRECURSOR_MASS=600.0<br>MAX_PRECURSOR_MASS=5000.0<br>MIN_PEP_LENGTH=8<br>MAX_PEP_LENGTH=30<br>MAX_FRAGMENT_CHARGE=3<br>REMOVE_METHIONINE=false<br>BATCH_SIZE=0<br>THEORETICAL_FRAGMENT_IONS_SUM_ONLY=false<br>FRAGMENT_BIN_OFFSET=0.0<br><br>USE_SPARSE_MATRIX=true<br>OUTPUT_FORAMT=PepXML<br>PRINT_EXPECT_SCORE=true<br><br><br># ------------------------------------------------------------------<br># MyriMatch Specific Parameters<br># ------------------------------------------------------------------<br><br>MIN_PEP_LENGTH=8<br>MAX_PEP_LENGTH=30<br>NUMBER_SPECTRUM_MATCHES=10<br>TIC_CUTOFF_PERCENTAGE=0.98<br>MAX_DYNMIC_MODS=2<br>MIN_TERMINI_CLEAVAGES=2<br>MIN_PRECURSOR_MASS=600.0<br>MAX_PRECURSOR_MASS=5000.0<br>USE_SMART_PLUS_THREE_MODEL=false<br>COMPUTE_XCORR=false<br>NUM_INTENSITY_CLASSES=3<br>CLASS_SIZE_MULTIPLIER=2<br>NUM_BATCHES=50<br>FRAGMENTATION_RULE=CID<br>MAX_PEAK_COUNT=300<br>OUTPUT_FORMAT=mzIdentML<br><br><br># ------------------------------------------------------------------<br># pNovo+ Specific Parameters<br># ------------------------------------------------------------------<br><br>NUMBER_PEPTIDES=10<br>LOWER_PRECURSOR_MASS=300<br>UPPER_PRECURSOR_MASS=5000<br>ACTIVATION_TYPE=HCD<br><br><br># ------------------------------------------------------------------<br># Tide Specific Parameters<br># ------------------------------------------------------------------<br><br>MIN_PEP_LENGTH=6<br>MAX_PEP_LENGTH=30<br>MIN_PRECURSOR_MASS=200.0<br>MAX_PRECURSOR_MASS=7200.0<br>MAX_VARIABLE_MODIFICATIONS_PER_TYPE_PER_PEPTIDE=2<br>MAX_VARIABLE_MODIFICATIONS_PER_PEPTID=255<br>DECOY_FORMAT=none<br>KEEP_TERMINAL_AMINO_ACIDS=NC<br>DECOY_SEED=1<br>OUTPUT_FOLDER_NAME=crux-output<br>PRINT_PEPTIDES=false<br>VERBOSITY=30<br>MONOISOTOPIC_PRECURSOR=true<br>CLIP_NTERM_METHIONINE=false<br>DIGESTION_TYPE=full-digest<br>COMPUTE_SP_SCORE=false<br>NUMBER_SPECTRUM_MATCHES=10<br>COMPUTE_EXACT_P_VALUES=false<br>MIN_SPECTRUM_MZ=0.0<br>MAX_SPECTRUM_MZ=null<br>MIN_SPECTRUM_PEAKS=20<br>SPECTRUM_CHARGES=all<br>REMOVE_PRECURSOR=false<br>REMOVE_PRECURSOR_TOLERANCE=1.5<br>PRINT_PROGRESS_INDICATOR_SIZE=1000<br>USE_FLANKING_PEAKS=false<br>USE_NEUTRAL_LOSS_PEAKS=false<br>MZ_BIN_WIDTH=0.02<br>MZ_BIN_OFFSET=0.0<br>CONCATENATE_TARGET_DECOY=false<br>STORE_SPECTRA_FILE_NAME=null<br>TEXT_OUTPUT=true<br>SQT_OUTPUT=false<br>PEPXML_OUTPUT=false<br>MZID_OUTPUT=false<br>PERCOLATOR_OUTPUT=false<br><br><br># ------------------------------------------------------------------<br># Novor Specific Parameters<br># ------------------------------------------------------------------<br><br>FRAGMENTATION=HCD<br>MASS_ANALYZER=FT<br></html>
```

**Comment by hbarsnes** [comment]
Interesting. Seems like you are running out of memory when trying to read the indexed spectrum file, i.e. the cms file. How large is the spectrum file in question? And can you try increasing the amount of memory given to SearchGUI?

**Comment by bernt-matthias** [comment]
The largest mgf file used as input is 3.2G the fasta is180M. 

For the Galaxy wrapper it would be really cool if the out of memory condition can be detected. Do you see a possibility for this?

**Comment by bernt-matthias** [comment]
What I mean is that for the Galaxy wrapper it would be more convenient if the messages that are now collected in the log file(s) would go to stderr. Maybe this could be controlled by a command line flag .. I understand that for end users the current behavior is convenient.

**Comment by hbarsnes** [comment]
> The largest mgf file used as input is 3.2G the fasta is180M.

And how much memory are you giving to SearchGUI? Is there any chance you can increase it?

> What I mean is that for the Galaxy wrapper it would be more convenient if the messages that are now collected in the log file(s) would go to stderr.

Yes, @CarlosHorro is looking into it.

**Comment by bernt-matthias** [comment]
> And how much memory are you giving to SearchGUI? Is there any chance you can increase it?

it was 10G (using `-Xmx 6g`). With the canges in https://github.com/galaxyproteomics/tools-galaxyp/pull/570 the out of memory condition is also detected and restarted automatically. Its currently running with 28G (-Xmx 18g) and got past the point where it failed so far.

FYI we use a trap (`trap ">&2 cat log_folder/*.log" EXIT;`) in the tool wrapper to make the content of the log files (which contain the oom message) available to Galaxy (we append it to stderr)
