### ISSUE TITLE
MSFG+ NegativeArraySizeException

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/searchgui#293]
During the execution of SearchGUI I observe the following in the errors:

```
MS-GF+ Release (v2021.01.08) (8 January 2021)
Java 11.0.8-internal (N/A)
Linux (amd64, version 3.10.0-1160.el7.x86_64)
Loading database files...
Warning: Sequence database contains 11 counts of letter 'B', which does not correspond to an amino acid.
Warning: Sequence database contains 934 counts of letter 'U', which does not correspond to an amino acid.
Warning: Sequence database contains 55491 counts of letter 'X', which does not correspond to an amino acid.
Warning: Sequence database contains 6 counts of letter 'Z', which does not correspond to an amino acid.
java.lang.NegativeArraySizeException: -1754156672
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.readSequence(CompactFastaSequence.java:542)
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:139)
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:89)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:234)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:113)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:61)
```

Is this something to worry about?

**Comment by hbarsnes** [comment]
No idea, but does not look good. I'd recommend contacting the MS-GF+ developers: https://github.com/MSGFPlus/msgfplus/issues.

**Comment by bernt-matthias** [comment]
Seems that I stumbled over this one before https://github.com/MSGFPlus/msgfplus/issues/43 .. 

Sequence DB seems to be to large (>3GB in my case).

Maybe SearchGUI could check for MSGF+ errors and abort?

**Comment by hbarsnes** [comment]
> Maybe SearchGUI could check for MSGF+ errors and abort?

Maybe, but it very much depends on how the individual search engines detect and report errors that may occur. For example, this particular error looks like one that should have been picked up by MS-GF+ and reported accordingly but instead it simply prints the stack trace.
