### ISSUE TITLE
Error message from SearchGUI after update to version 4.0.29

### ISSUE THREAD

**Issue by MNTNguyen** [compomics/searchgui#300]
Dear SearchGUI developers, 
after I updated SearchGUI to version 4.0.29 and PeptideShaker to ver 2.0.21, I got the error message "Overflow detected." right after starting the search (direct in Importing spectrum files).
I've tried with several mfg files, also those that I have succesfully had the search run before. Same error message.
I later re-install version 4.0.28 and PeptideShaker 2.0.20, the importing step is completed but I got another error message: "Converting to peak list - Error: Null". When I opened previous projects, the panels Peptide spectrum matches and Spectrum & Fragment Ions cannot be loaded too. They are empty.
Please let me know how to overcome these problems.
Thanks a lot.
![210423_SearchGUIerror](https://user-images.githubusercontent.com/83227918/116098446-60e26400-a6ab-11eb-930b-b1944f309f5d.png)
![210426_SearchGUIerror](https://user-images.githubusercontent.com/83227918/116098450-62139100-a6ab-11eb-8420-15682268730b.png)
![210426_PeptideShakerError](https://user-images.githubusercontent.com/83227918/116098898-b880cf80-a6ab-11eb-8aa4-83df56b0e728.png)

**Comment by iquasere** [comment]
I still get this error with 4.0.31

**Comment by MNTNguyen** [comment]
Me too.

João Sequeira ***@***.***> schrieb am Mi. 28. Apr. 2021 um
12:12:

**Comment by hbarsnes** [comment]
Do you get the error for both SearchGUI and PeptideShaker? Or only for SearchGUI?

Can you have a look at the resource settings for SearchGUI? You'll find them via Edit > Resource Settings? Please make sure that the folders listed there are valid folders (and not the ones from the custom settings file I included by mistake in a recent release).

It would also be great if you could send me the SearchGUI log file? You'll find it via Help > Bug Report.

**Comment by iquasere** [comment]
![image](https://user-images.githubusercontent.com/16226371/116390384-e2560580-a815-11eb-9e61-278c83eacf6a.png)

All of these are valid folders, except maybe for the first one, don't know what ```Default``` means here.

**Comment by hbarsnes** [comment]
> All of these are valid folders, except maybe for the first one, don't know what Default means here.

Yes, looks good. I don't see any problems there. Any more details in the log file?

**Comment by iquasere** [comment]
Not really :|

```
# ------------------------------------------------------------------
# SearchGUI 4.0.31 Report File
#
# Originally saved by: Utilizador @ DESKTOP-H77L7RB
#                  on: 28 abr 2021, 11:10
#                  as: SearchGUI Report 2021-04-28 11.10.35.html
# ------------------------------------------------------------------



Wed Apr 28 11:10:35 BST 2021        Importing spectrum files.
Wed Apr 28 11:10:35 BST 2021        Importing spectrum files completed (32.0 milliseconds).
Wed Apr 28 11:10:35 BST 2021        Converting spectrum file CS1_1uL.mgf to peak list.
Wed Apr 28 11:10:35 BST 2021        Error: null
Wed Apr 28 11:10:35 BST 2021        An error occurred while running SearchGUI. Please contact the developers.
Wed Apr 28 11:10:35 BST 2021        The search or processing did not finish properly!

Wed Apr 28 11:10:35 BST 2021        Searching Canceled!
# ------------------------------------------------------------------
# General Search Parameters
# ------------------------------------------------------------------

ENZYME0=Trypsin, Specific, 2 missed cleavages
FIXED_MODIFICATIONS=Carbamidomethylation of C
VARIABLE_MODIFICATIONS=Oxidation of M
REFINEMENT_FIXED_MODIFICATIONS=Carbamidomethylation of C
REFINEMENT_VARIABLE_MODIFICATIONS=
PRECURSOR_MASS_TOLERANCE=10.0
PRECURSOR_MASS_TOLERANCE_UNIT=ppm
FRAGMENT_MASS_TOLERANCE=0.5
FRAGMENT_MASS_TOLERANCE_UNIT=Da
PPM_TO_DA_CONVERSION_REF_MASS=2000.0
FORWARD_FRAGMENT_ION_TYPE=b
FRAGMENT_ION_TYPE_2=y
PRECURSOR_CHARGE_LOWER_BOUND=2
PRECURSOR_CHARGE_UPPER_BOUND=4
ISOTOPIC_CORRECTION_LOWER_BOUND=0
ISOTOPIC_CORRECTION_UPPER_BOUND=1


# ------------------------------------------------------------------
# OMSSA Specific Parameters
# ------------------------------------------------------------------

EVALUE_CUTOFF=100.0
MAXIMUM_HITLIST_LENGTH=10
PRECURSOR_ELIMINATION=false
PRECURSOR_SCALING=true
MINIMAL_PEPTIDE_SIZE=8
MAXIMAL_PEPTIDE_SIZE=30
PRECURSOR_CHARGE_TO_CONSIDER_MULTIPLY_CHARGED_FRAGMENTS=3
CHARGE_ESTIMATION=true
OUTPUT_TYPE=OMX
MEMORY_MAPPED_SEQUENCES=false
MASS_TO_CONSIDER_EXACT_NEUTRON_MASS=1446.94
LOW_INTENSITY_CUTOFF=0.0
HIGH_INTENSITY_CUTOFF=0.2
INTENSITY_INCREMENT=5.0E-4
SINGLE_CHARGE_WINDOW_WIDTH=27
DOUBLE_CHARGE_WINDOW_WIDTH=14
SINGLE_CHARGE_WINDOW_NPEAKS=2
DOUBLE_CHARGE_WINDOW_NPEAKS=2
MAX_HITS_PER_SPECTRUM_PER_CHARGE=30
MIN_ANNOTATED_INTENSE_PEAKS=6
MIN_ANNOTATED_PEAKS=2
MIN_PEAKS=4
CLEAVE_TERMINAL_METHIONINE=true
MAX_MZ_LADDERS=128
MAX_FRAGMENT_CHARGE=2
FRACTION_PEAKS_FOR_CHARGE_1_ESTIMATION=0.95
AUTO_DETERMINE_CHARGE_ONE=true
SEARCH_POSITIVE_IONS=true
MIN_PERCURSORS_PER_SPECTRUM=1
FORWARD_FRAGMENTS_FIRST=false
REWIND_FRAGMENTS=true
FRAGMENTS_PER_SERIES=100
CORRELATION_CORRECTION_SCORE=true
CONSECUTIVE_ION_PROBABILITY=0.5
ITERATIVE_SEARCH_SEQUENCE_EVALUE=0.0
ITERATIVE_SEARCH_SPECTRUM_EVALUE=0.01
ITERATIVE_SEARCH_REPLACEMENT_EVALUE=0.0


# ------------------------------------------------------------------
# MetaMorpheus Specific Parameters
# ------------------------------------------------------------------

MIN_PEPTIDE_LENGTH=8
MAX_PEPTIDE_LENGTH=30
SEARCH_TYPE=Classic
NUM_PARTITIONS=1
DISSOCIATION_TYPE=HCD
MAX_MODS_FOR_PEPTIDE=2
INITIATOR_METHIONINE_BEHAVIOR=Variable
SCORE_CUTOFF=5.0
USE_DELTA_SCORE=false
FRAGMENTATION_TERMINUS=Both
MAX_FRAGMENTATION_SIZE=30000.0
MASS_DIFF_ACCEPTOR_TYPE=OneMM
WRITE_MZID=true
WRITE_PEPXML=false
USE_PROVIDED_PRECURSOR=true
DO_PREC_DECONVOLUTION=true
DECONVOLUTION_INT_RATIO=3.0
DECONVOLUTION_MASS_TOL=4.0
DECONVOLUTION_MASS_TOL_TYPE=PPM
TRIM_MS1_PEAKS=false
TRIM_MSMS_PEAKS=true
NUM_PEAKS_PER_WINDOWS=200
MIN_ALLOWED_INT_RATIO_TO_BASE_PEAK=0.01
WINDOW_WITH_THOMPSON=null
NUM_WINDOWS=null
NORMALIZE_PEAKS_ACROSS_ALL_WINDOWS=false
MOD_PEPTIDES_ARE_DIFFERENT=false
NO_ONE_HIT_WONDERS=false
SEARCH_TARGET=true
DECOY_TYPE=None
MAX_MOD_ISOFORMS=1024
MIN_VARIANT_DEPTH=1
MAX_HETROZYGOUS_VARIANTS=4
RUN_GPTM=false
GPTMS=Common Biological, Common Artifact, Metal


# ------------------------------------------------------------------
# X!Tandem Specific Parameters
# ------------------------------------------------------------------

DYNAMIC_RANGE=100.0
NUMBER_OF_PEAKS=50
MIN_FRAG_MASS=200.0
MIN_NUMBER_OF_PEAKS=5
NOISE_SUPPRESSION=NO
PARENT_MONOISOTOPIC_MASS_ISOTOPE_ERROR=YES
MIN_PREC_MASS=500.0
PROTEIN_QUICK_ACETYL=YES
QUICK_PYROLIDONE=YES
PROTEIN_PTM_COMPLEXITY=6.0
STP_BIAS=NO
REFINE=YES
REFINE_SEMI=NO
REFINE_POINT_MUTATIONS=NO
REFINE_SPECTRUM_SYNTHESIS=YES
REFINE_UNANTICIPATED_CLEABAGES=YES
REFINE_SNAPS=YES
REFINE_MAX_EVALUE=0.01
POTENTIAL_MODIFICATIONS_FOR_FULL_REFINEMENT=NO
EVALUE_CUTOFF=0.01
SKYLINE_PATH=
OUTPUT_RESULTS=all
OUTPUT_PROTEINS=YES
OUTPUT_SEQUENCES=NO
OUTPUT_SPECTRA=YES
OUTPUT_HISTOGRAMS=NO


# ------------------------------------------------------------------
# PepNovo+ Specific Parameters
# ------------------------------------------------------------------

HIT_LIST_LENGTH=10
CORRECT_PRECURSOR_MASS=false
DISCARD_LOW_QUALITY_SPECTRA=true
FRAGMENTATION_MODEL=CID_IT_TRYP
GENERATE_QUERY=false


# ------------------------------------------------------------------
# Andromeda Specific Parameters
# ------------------------------------------------------------------

MIN_PEPTIDE_LENGHT_NO_ENZYME=8
MAX_PEPTIDE_LENGHT_NO_ENZYME=30
MAX_PEPTIDE_MASS=4600.0
NUMBER_SPECTRUM_MATCHES=10
MAX_PTMS=5
FRAGMENTATION_METHOD=CID
WATER_LOSS=true
AMMONIA_LOSS=true
SEQUENCE_DEPENDENT_NEUTRAL_LOSS=true
EQUAL_IL=false
FRAGMENT_ALL=false
EMPERICAL_CORRECTION=true
HIGHER_CHARGE=true
MAX_COMBINATIONS=250
TOP_PEAKS=8
TOP_PEAKS_WINDOW=100
DECOY_MODE=none


# ------------------------------------------------------------------
# MS Amanda Specific Parameters
# ------------------------------------------------------------------

SEARCH_DECOY=false
REPORT_BOTH_BEST_HITS_FOR_TD=true
INSTRUMENT_ID=b, y
MONOISOTOPIC=true
MAX_RANK=10
PERFORM_DEISOTOPING=true
MAX_MODIFICATIONS=3
MAX_VARIABLE_MODIFICATIONS=4
MAX_MODIFICATIONS_SITES=6
MAX_NEUTRAL_LOSSES=1
MAX_NEUTRAL_LOSSES_PER_MODIFICATION=2
MIN_PEPTIDE_LENGTH=8
MAX_PEPTIDE_LENGTH=30
MAX_LOADED_PROTEINS=100000
MAX_LOADED_SPECTRA=2000
OUTPUT_FORMAT=csv


# ------------------------------------------------------------------
# MS-GF+ Specific Parameters
# ------------------------------------------------------------------

SEARCH_DECOY=false
INSTRUMENT_ID=3
FRAGMENTATION_ID=3
PROTOCOL_ID=0
MIN_PEP_LENGTH=8
MAX_PEP_LENGTH=30
NUMBER_SPECTRUM_MATCHES=10
ADDITIONAL_OUTPUT=false
NUMBER_OF_TOLERABLE_TERMINI=2
MAX_NUMBER_MODIFICATIONS=2
NUMBER_TASKS=null


# ------------------------------------------------------------------
# DirecTag Specific Parameters
# ------------------------------------------------------------------

TIC_CUTOFF_PERCENTAGE=100.0
MAX_PEAK_COUNT=100
NUM_INTENSITY_CLASSES=3
ADJUST_PRECURSOR_MASS=false
MIN_PRECUSOR_ADJUSTMENT=-0.5
MAX_PRECUSOR_ADJUSTMENT=1.5
PRECUSOR_ADJUSTMENT_STEP=0.1
NUM_CHARGE_STATES=3
OUTPUT_SUFFIX=
USE_CHARGE_STATE_FROM_MS=true
DUPLICATE_SPECTRA=true
DEISOTOPING_MODE=0
ISOTOPE_MZ_TOLERANCE=0.25
COMPLEMENT_MZ_TOLERANCE=0.1
TAG_LENGTH=4
MAX_DYNAMIC_MODS=2
MAX_TAG_COUNT=10
INTENSITY_SCORE_WEIGHT=1.0
MZ_FIDELITY_SCORE_WEIGHT=1.0
COMPLEMENT_SCORE_WEIGHT=1.0


# ------------------------------------------------------------------
# Comet Specific Parameters
# ------------------------------------------------------------------

NUMBER_SPECTRUM_MATCHES=10
MAX_VARIABLE_MODS=10
REQUIRE_VARIABLE_MODS=false
MIN_PEAKS=10
MIN_PEAKS_INTENSITY=0.0
REMOVE_PRECURSOR=0
REMOVE_PRECURSOR_TOLERANCE=1.5
LOWER_CLEAR_MZ_RANGE=0.0
UPPER_CLEAR_MZ_RANGE=0.0
ENZYME_TYPE=2
ISOTOPE_CORRECTION=1
MIN_PRECURSOR_MASS=600.0
MAX_PRECURSOR_MASS=5000.0
MIN_PEP_LENGTH=8
MAX_PEP_LENGTH=30
MAX_FRAGMENT_CHARGE=3
REMOVE_METHIONINE=false
BATCH_SIZE=0
THEORETICAL_FRAGMENT_IONS_SUM_ONLY=false
FRAGMENT_BIN_OFFSET=0.25

USE_SPARSE_MATRIX=true
OUTPUT_FORAMT=PepXML
PRINT_EXPECT_SCORE=true


# ------------------------------------------------------------------
# MyriMatch Specific Parameters
# ------------------------------------------------------------------

MIN_PEP_LENGTH=8
MAX_PEP_LENGTH=30
NUMBER_SPECTRUM_MATCHES=10
TIC_CUTOFF_PERCENTAGE=0.98
MAX_DYNMIC_MODS=2
MIN_TERMINI_CLEAVAGES=2
MIN_PRECURSOR_MASS=600.0
MAX_PRECURSOR_MASS=5000.0
USE_SMART_PLUS_THREE_MODEL=false
COMPUTE_XCORR=false
NUM_INTENSITY_CLASSES=3
CLASS_SIZE_MULTIPLIER=2
NUM_BATCHES=50
FRAGMENTATION_RULE=CID
MAX_PEAK_COUNT=300
OUTPUT_FORMAT=mzIdentML


# ------------------------------------------------------------------
# pNovo+ Specific Parameters
# ------------------------------------------------------------------

NUMBER_PEPTIDES=10
LOWER_PRECURSOR_MASS=300
UPPER_PRECURSOR_MASS=5000
ACTIVATION_TYPE=HCD


# ------------------------------------------------------------------
# Tide Specific Parameters
# ------------------------------------------------------------------

MIN_PEP_LENGTH=6
MAX_PEP_LENGTH=30
MIN_PRECURSOR_MASS=200.0
MAX_PRECURSOR_MASS=7200.0
MAX_VARIABLE_MODIFICATIONS_PER_TYPE_PER_PEPTIDE=2
MAX_VARIABLE_MODIFICATIONS_PER_PEPTID=255
DECOY_FORMAT=none
KEEP_TERMINAL_AMINO_ACIDS=NC
DECOY_SEED=1
OUTPUT_FOLDER_NAME=crux-output
PRINT_PEPTIDES=false
VERBOSITY=30
MONOISOTOPIC_PRECURSOR=true
CLIP_NTERM_METHIONINE=false
DIGESTION_TYPE=full-digest
COMPUTE_SP_SCORE=false
NUMBER_SPECTRUM_MATCHES=10
COMPUTE_EXACT_P_VALUES=false
MIN_SPECTRUM_MZ=0.0
MAX_SPECTRUM_MZ=null
MIN_SPECTRUM_PEAKS=20
SPECTRUM_CHARGES=all
REMOVE_PRECURSOR=false
REMOVE_PRECURSOR_TOLERANCE=1.5
PRINT_PROGRESS_INDICATOR_SIZE=1000
USE_FLANKING_PEAKS=false
USE_NEUTRAL_LOSS_PEAKS=false
MZ_BIN_WIDTH=0.02
MZ_BIN_OFFSET=0.0
CONCATENATE_TARGET_DECOY=false
STORE_SPECTRA_FILE_NAME=null
TEXT_OUTPUT=true
SQT_OUTPUT=false
PEPXML_OUTPUT=false
MZID_OUTPUT=false
PERCOLATOR_OUTPUT=false


# ------------------------------------------------------------------
# Novor Specific Parameters
# ------------------------------------------------------------------

FRAGMENTATION=HCD
MASS_ANALYZER=FT
```

**Comment by hbarsnes** [comment]
@iquasere I meant the error log file. You'll find it via Help > Bug Report.

**Comment by iquasere** [comment]
```
java.lang.IllegalStateException: Overflow detected
	at io.airlift.compress.zstd.Util.checkState(Util.java:59)
	at io.airlift.compress.zstd.BitOutputStream.close(BitOutputStream.java:85)
	at io.airlift.compress.zstd.HuffmanCompressor.compressSingleStream(HuffmanCompressor.java:130)
	at io.airlift.compress.zstd.HuffmanCompressor.compress4streams(HuffmanCompressor.java:75)
	at io.airlift.compress.zstd.ZstdFrameCompressor.encodeLiterals(ZstdFrameCompressor.java:333)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressBlock(ZstdFrameCompressor.java:224)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressFrame(ZstdFrameCompressor.java:172)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compress(ZstdFrameCompressor.java:145)
	at io.airlift.compress.zstd.ZstdCompressor.compress(ZstdCompressor.java:45)
	at com.compomics.util.io.compression.ZstdUtils.zstdCompress(ZstdUtils.java:98)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileWriter.compress(CmsFileWriter.java:213)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileWriter.addSpectrum(CmsFileWriter.java:129)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.writeCmsFile(MsFileHandler.java:223)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.register(MsFileHandler.java:149)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2518)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.DirectByteBuffer.getDouble(Unknown Source)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileReader.getSpectrum(CmsFileReader.java:163)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.getSpectrum(MsFileHandler.java:252)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileExporter.writeMgfFile(MsFileExporter.java:206)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2584)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by hbarsnes** [comment]
@iquasere Thanks! I will look into it and get back to you. Would it also be possible for you to share one of the spectrum files causing the issue?

**Comment by iquasere** [comment]
You can download them [here](https://we.tl/t-TZrW87woBD).

I also included the database, might be involved.

**Comment by hbarsnes** [comment]
@iquasere Thanks again. I will dig a bit deeper and get back to you.

**Comment by hbarsnes** [comment]
@iquasere Just wanted to confirm that I get the same issue with your mgf files. Works fine for other mgf files though. How were the mgf files created?

**Comment by iquasere** [comment]
With MS Convert. [Here](https://we.tl/t-NrO60JALnO) follow the original wiff files, if you want to try and create functioning mgfs

**Comment by MNTNguyen** [comment]
@hbarsnes: Hi, 
The bug report looks a bit different by me. Therefore I will just send you already all you asked up to now in this thread: resource settings, error message, bug report, spectrum mgf file and database FASTA file. Download link [here](https://we.tl/t-e1xVCIn4Md).
This mgf file I have already analysed before update without issue. Thank you :)

**Comment by hbarsnes** [comment]
@MNTNguyen Thanks! I think it comes down to the same underlying problem though (which seems to be an issue with the compression library we use). If you delete the created cms file (it should be located next to your mgf file) and try again, I'm pretty sure you will get the same error message as indicated in @iquasere error log file?

**Comment by MNTNguyen** [comment]
@hbarsnes: not really - after deleting cms file, my error message is:
Wed Apr 28 14:09:33 CEST 2021        Importing spectrum files.
Wed Apr 28 14:09:33 CEST 2021        Error: Overflow detected
Wed Apr 28 14:09:33 CEST 2021        An error occurred while running SearchGUI. Please contact the developers.
Wed Apr 28 14:09:33 CEST 2021        The search or processing did not finish properly!

Wed Apr 28 14:09:33 CEST 2021        Searching Canceled!

**Comment by MNTNguyen** [comment]
in the error log file a big part, the same - yes. Mine is different beginning from the unknown source part.
[2021-04-28 ohne cms Bug report.docx](https://github.com/compomics/searchgui/files/6391683/2021-04-28.ohne.cms.Bug.report.docx)

**Comment by iquasere** [comment]
@hbarsnes any luck running those wiff? I did tried running with the MSConvert integrated in SearchGUI, but as expected the results were the same

**Comment by hbarsnes** [comment]
@iquasere I have found a potential fix that seems to work. Just have to do some additional testing to make sure.

**Comment by hbarsnes** [comment]
The issue should now hopefully be solved and new versions of both tools have been released. If you still experience problems, please let me know and I'll reopen the issue.

**Comment by iquasere** [comment]
It did seem to improve on my system, still it fails: [report.txt](https://github.com/compomics/searchgui/files/6399139/report.txt)

Another problem I have seen is that trying to give more memory with ```java -Xmx4G -jar SearchGUI-4.0.32.jar``` does not seem to work
```
"C:\Users\Utilizador\anaconda3\Library\bin\java" -splash:resources\conf\searchgui-splash.png -Xms128M -Xmx1024M -cp "C:\Users\Utilizador\Desktop\SearchGUI-4.0.32\SearchGUI-4.0.32.jar" eu.isas.searchgui.gui.SearchGUI
```

**Comment by hbarsnes** [comment]
@iquasere Well, at least this issue should be easier to fix. Basically MS-GF+ is running out of memory. You can increase the amount of memory given to SearchGUI, and correspondingly MS-GF+, via Edit > Java Settings > Memory.

**Comment by MNTNguyen** [comment]
They work perfectly fine for me (i have rerun with 5 old mgfs file and they
yielded the same results).
Thanks a lot!

**Comment by iquasere** [comment]
It seems to be working, however I only get around 50 confident identifications, when with previous versions I got much more confident identifications. Do you get the same results, Harald?

**Comment by hbarsnes** [comment]
@iquasere Which older versions are you comparing against? And can you verify that you are using the exact same search settings?

**Comment by iquasere** [comment]
With SearchGUI 3.3.20 and Peptide-Shaker 1.16.42, I get (455/2338) 286 confident, 169 doubtful, while with these last versions I get much less (some 50 confident). Search parameters are the default

![image](https://user-images.githubusercontent.com/16226371/116700687-f6893680-a9be-11eb-9738-8a5f6015ff01.png)

**Comment by hbarsnes** [comment]
@iquasere The use of 0.5 Da for the fragment ion tolerance looks very high to me? Are you sure this is what you used in the earlier versions? Which search engines are you using btw?

**Comment by hbarsnes** [comment]
@iquasere Here's what I get if I use the search settings above on the data you sent me earlier when using only MS-GF+:

![MS-GF+ only](https://user-images.githubusercontent.com/13151214/116708914-77046300-a9d0-11eb-96e8-532436da1d0f.png)

In other words, much more than 50 proteins confidently identified.

**Comment by iquasere** [comment]
I was setting the wrong value for precursor tolerance, you're right. But adjusting it to 0.02 Da, I get 330 confident, 162 doubtful with SearchGUI 3.3.20, PS 1.16.42, and 51 c, 5 d for 4.0.32 and 2.0.25, respectively. Can you confirm that 4.0.32, 2.0.25 give these small identifications, using precursor tolerance with 0.02 Da?

**Comment by hbarsnes** [comment]
@iquasere Which search engines are you using?

**Comment by iquasere** [comment]
Myri-match, X!Tandem and MS-GF+

**Comment by hbarsnes** [comment]
@iquasere Yes, I see similar numbers to what you are seeing when comparing the old and new versions. I will dig deeper and get back to you. Would be great if you could set up a new issue under PeptideShaker though? As this new problem is not really related to the initial spectrum file issue?
