### ISSUE TITLE
MetaMorpheus issue with TMT mods?

### ISSUE THREAD

**Issue by jcanderan** [compomics/searchgui#321]
I'm getting the following issue with MetaMorpheus:

```
java.lang.NullPointerException
        at eu.isas.searchgui.processbuilders.MetaMorpheusProcessBuilder.getModificationFormattedForMetaMorpheus(MetaMorpheusProcessBuilder.java:730)
        at eu.isas.searchgui.processbuilders.MetaMorpheusProcessBuilder.createModificationsFile(MetaMorpheusProcessBuilder.java:595)
        at eu.isas.searchgui.processbuilders.MetaMorpheusProcessBuilder.<init>(MetaMorpheusProcessBuilder.java:136)
        at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:3185)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

If I had to guess, the problem is using TMT10 mods. SearchGUI was run with: 

`-fixed_mods 'Carbamidomethylation of C,TMT 10-plex of K,TMT 10-plex of peptide N-term' -variable_mods 'Oxidation of M'`

I've had no problems using other search engines or using MetaMorpheus without TMT10.

Edit: I tried various other mods and occasionally have the issue but it seems to always happen with TMT10.

Thanks!

**Comment by hbarsnes** [comment]
Thanks for letting us know! The issue should now been fixed and a new version of SearchGUI (v4.1.14) is available.
