### ISSUE TITLE
Can't run searchGUI on Linux

### ISSUE THREAD

**Issue by zys7777** [compomics/searchgui#327]
I install SearchGUI in conda using the command

conda install -c conda-forge -c bioconda searchgui 

And I run 

java -cp /myfolder/SearchGUI-3.3.9.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/myfolder/F08_Rep1.mgf" -fasta_file "/myfolder/1.fasta" -output_folder "/myfolder" -id_params "/myfolder/peptideshaker1.par" -xtandem 1 -myrimatch 1 -ms_amanda 1 -msgf 1 -omssa 1 -comet 1 -tide 1 -andromeda 1 -novor 1 -directag 1 -threads 16

The SearchGUI just don't start. Is there anything wrong?

**Comment by zys7777** [comment]
It reports error, see below

<img width="560" alt="image" src="https://user-images.githubusercontent.com/111046780/184278496-07af270b-f4e1-4cff-89fb-4e9cc8a76d1c.png">

log file:

java.io.FileNotFoundException: conf/databases.xml (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at eu.isas.searchgui.processbuilders.AndromedaProcessBuilder.createDatabaseFile(AndromedaProcessBuilder.java:203)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2308)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hbarsnes** [comment]
Could it be the case that you are running this on Mac or Linux? As Andromeda is only supported in Windows. Try turning off Andromeda (-andromeda 0) and see if that helps?

**Comment by zys7777** [comment]
Problem solved. Thanks! You help me a lot.
