### ISSUE TITLE
Error: File exceeds memory mapped reader max buffer size.

### ISSUE THREAD

**Issue by esraaelmligy** [compomics/searchgui#371]
Greetings, I am trying to run a XTandem! search on a benchmark ms dataset and upon conversion of raw files, one of my mgf files is causing an error that seems to because of its large size (6.4 Gb) I have seen previous issues regarding this error and have tried using the --mgf-split options but it seems to be doing nothing so i do not know if i am using it wrong or what.

**This is the command i am running with:**

java -cp /home/esraa/SearchGUI-4.2.17/SearchGUI-4.2.17.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files ./HEK293-acid-highAGC-360minDE15-75um25cm-2.mzML -id_params ./id_params.par -fasta_file ./final_database.fasta -output_folder ./haplotypecaller -xtandem 1 -output_data 1 -mgf_check_size 1 -mgf_splitting 1000

**This is my log:**

Tue Mar 19 09:34:09 EET 2024: SearchGUI version 4.2.17.
Memory given to the Java virtual machine: 8338276352.
Total amount of memory in the Java virtual machine: 532676608.
Free memory: 510274144.
Java version: 17.0.10.
java.io.IOException: File exceeds memory mapped reader max buffer size.
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileWriter.addSpectrum(CmsFileWriter.java:109)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.writeCmsFile(MsFileHandler.java:224)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.register(MsFileHandler.java:150)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2856)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by esraaelmligy** [comment]
Oh my mistake, i gave you a wrong command, anyhow i have tried the option with the mgf file instead and still face the same problem

**java -cp /home/esraa/SearchGUI-4.2.17/SearchGUI-4.2.17.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files ./HEK293-acid-highAGC-360minDE15-75um25cm-2.mgf -id_params ./id_params.par -fasta_file ./final_database.fasta -output_folder ./haplotypecaller -xtandem 1 -output_data 1 -mgf_check_size 1 -mgf_splitting 1000**

Log:

**Tue Mar 19 13:08:00 EET 2024: SearchGUI version 4.2.17.
Memory given to the Java virtual machine: 8338276352.
Total amount of memory in the Java virtual machine: 532676608.
Free memory: 510274144.
Java version: 17.0.10.
java.io.IOException: File exceeds memory mapped reader max buffer size.
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileWriter.addSpectrum(CmsFileWriter.java:109)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.writeCmsFile(MsFileHandler.java:224)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.register(MsFileHandler.java:150)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2856)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)**

**Comment by hbarsnes** [comment]
Have you tried reducing the mgf_splitting value? Perhaps you can try 500 instead of 1000?

**Comment by esraaelmligy** [comment]
Yes I have tried with 500 and even with 200 but it seems to be doing nothing and gives the same error

**Comment by hbarsnes** [comment]
You are now providing the mgf and not the mzml file right? Does it actually do any splitting? I.e. does it it create smaller mgf files each containing a subset of your original mgf file? And if so, does the error show up for all of these smaller mgf files or just for some of them?

**Comment by esraaelmligy** [comment]
Yes i am using the mgf file and no it is not doing any splitting it seems to be running as if i have not enabled the option

**Comment by hbarsnes** [comment]
You are correct! It seems like this feature was removed at some point and not re-added. I will look into whether it is possible reimplement it. Although it would probably be better if we properly fixed the "File exceeds memory mapped reader max buffer size" error instead. I will keep you posted, although I cannot say when or how soon I will get the time to dig deeper into it.

**Comment by esraaelmligy** [comment]
Okay thank you so much! I will be waiting for any further update.

**Comment by hbarsnes** [comment]
I've just released SearchGUI version 4.3.8 that should take care of the problem with the buffer size. If this is not the case, please let me know and I'll reopen the issue.
