### ISSUE TITLE
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,50]

### ISSUE THREAD

**Issue by marinacd** [compomics/searchgui#379]
Hello, I keep getting errors which I don't know if are related to an issue with my files or the memory allocation. 

I see both this in the log file:
`javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,50]
Message: White spaces are required between publicId and systemId.
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at com.compomics.software.autoupdater.MetaDataXMLParser.<init>(MetaDataXMLParser.java:31)
	at com.compomics.software.autoupdater.WebDAO.getLatestVersionNumberFromRemoteRepo(WebDAO.java:37)
	at com.compomics.software.autoupdater.WebDAO.newVersionReleased(WebDAO.java:105)
	at com.compomics.software.autoupdater.DownloadLatestZipFromRepo.downloadLatestZipFromRepo(DownloadLatestZipFromRepo.java:306)
	at eu.isas.searchgui.gui.PeptideShakerParametersDialog$15.run(PeptideShakerParametersDialog.java:942)

`

and the following in the report:
- Load spectra: Error - new(pfFastXcorrDataNL[43193851]). bad_alloc: bad allocation.
 
Comet ran out of memory. Look into "spectrum_batch_size"
 
parameters to address mitigate memory use.
 

I have tried changing the spectrum batch size and allocating more memory but I am unsure if it's just my files being incorrectly formatted or my computer not being able to handle the search, since I did run it previously and it worked in another computer, but I also redowloaded the files so the issue could be there too.

I'd appreciate any help, 

Thanks!

**Comment by hbarsnes** [comment]
Hi! The first error you can ignore. It just related to checking whether a more recent version of the tool is available. The second seems to be an issue inside Comet and therefore not something we can do much about ourselves. I'd recommend contacting the Comet developers directly via: https://groups.google.com/g/comet-ms.
