### ISSUE TITLE
MyriMatch and MS-GF+ fail to read MGF with unspecified precursor charge (empty CHARGE= line)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/searchgui#44]
```
> What steps will reproduce the problem?
Running search with an MGF that contains spectra with precursor ion charge not 
specified (i.e. containing a line with "CHARGE=")

> What is the expected output? What do you see instead?
MyriMatch, MS Amanda, and MS-GF+ fail to read the MGF (output from each pasted 
below, while X!Tandem, OMSSA and Comet succeed.

[SpectrumList_MGF::parseSpectrum] Error parsing line at offset 162994: CHARGE=

Error parsing mgf file at or after spectrum 'Cmpd 296, AutoMSn(542.5984), 12.0 
min (id=5910974534152696)'.

Reading spectra...
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(Unknown Source)
	at edu.ucsd.msjava.parser.MgfSpectrumParser.readSpectrum(MgfSpectrumParser.java:103)
	at edu.ucsd.msjava.msutil.SpectraIterator.next(SpectraIterator.java:54)
	at edu.ucsd.msjava.msutil.SpectraIterator.next(SpectraIterator.java:1)
	at edu.ucsd.msjava.msutil.SpecKey.getSpecKeyList(SpecKey.java:79)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:282)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:142)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:80)


> What version of the product are you using? On what operating system?
SearchGUI 1.26.4, on Windows 7 Enterprise 64-bit.

> Please provide any additional information below.
This problem was previously reported as issue 32 and was fixed.

> If the reported issue resulted in the tool crashing, please
> also upload the file called SearchGUI.log (found in the
> SearchGUI-X.Y.Z\resources folder).
I am unable to attach the log file ("Issue attachment storage quota exceeded").

```

Original issue reported on code.google.com by `EssArrAi...@gmail.com` on 19 Mar 2015 at 9:39

**Comment by hbarsnes** [comment]
As MS-GF+ and MyriMatch are not actively maintained anymore a fix for the empty charge element will most likely not be implemented for these search engines. And as an mgf file with such lines could be considered to be incorrect, we've therefore decided to close the issue. Users having mgf files with this issue are recommended to do a search and replace to remove the lines with the empty charge tags.
