### ISSUE TITLE
Error loading SearchGUI 2.1.3 from PeptideShaker 1.1.2 (MacOS El Capitan) - java version "1.6.0_65"

### ISSUE THREAD

**Issue by stemicha** [compomics/searchgui#66]
java version "1.6.0_65"
- have to use older version for running old programs as well.

SearchGUI log:

<ERROR>

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/compomics/software/CompomicsWrapper : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at eu.isas.searchgui.SearchGUIZipFileChecker.<init>(SearchGUIZipFileChecker.java:61)
	at eu.isas.searchgui.SearchGUIZipFileChecker.main(SearchGUIZipFileChecker.java:71)

The command line executed:
java -jar /Applications/SearchGUI-2.1.3/SearchGUI-2.1.3.jar 

</ERROR>

**Comment by hbarsnes** [comment]
The problem seems to be that you have a very old Java version. You are using Java 1.6.0_65, while the current Java aversion is 1.8.0_60. Please update to the latest version here: http://www.oracle.com/technetwork/java/javase/downloads.

Please let us know if this solves the problem.

**Comment by mvaudel** [comment]
Hi again,

New versions have been released which should work on java 1.6. If this does not solve your problem, please contact us and we will reopen the issue.

If we may ask, is there any specific reason why you cannot update java?

Best regards,

Marc
