### ISSUE TITLE
Zipped searchGUI export crashing PeptideShaker

### ISSUE THREAD

**Issue by cdlawless** [compomics/searchgui#78]
Afternoon Guys

I'm having trouble with processing the zipped output from searchGUI (v2.4.1) with PeptideShaker (v1.4.0). 

The searchGUI command is:
java -Xms4096M -Xmx131072M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.4.1/SearchGUI-2.4.1.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/lustre/scratch/mjfidcl
2/DDIP/Embryo_fractions/Qexactive/new_mgfs" -output_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/Qexactive/FDR_Comparison/MDV3_Qex_18012016/ -id_params /mnt/lustre/scratch/mjf
idcl2/DDIP/Embryo_fractions/Qexactive/FDR_Comparison/Qex_MDV3.par -output_option 0 -output_data 1 -mgf_splitting 2000 -temp_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_f
ractions/Qexactive/FDR_Comparison/temp -xtandem 0 -msgf 1 -omssa 0 -myrimatch 0 -comet 0 -tide 0 -ms_amanda 0 -andromeda 0 

I then run the PeptideShaker command:
java -Xms1024m -Xmx131072M -cp /mnt/fls01-home01/mjfidcl2/scratch/PeptideShaker/PeptideShaker-1.4.0/PeptideShaker-1.4.0.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment Qex_MDV3 
-sample Qex_MDV3 -replicate 1 -identification_files "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/Embryo_fractions/Qexactive/FDR_Comparison/MDV3_Qex_18012016/searchgui_out.zip" -out "/mnt/fls01-home01/m
jfidcl2/scratch/DDIP/Embryo_fractions/Qexactive/FDR_Comparison/PS_Qex_MDV3_output/" -ptm_score 1 -out_reports "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/Embryo_fractions/Qexactive/FDR_Compar
ison/PS_Qex_MDV3_reports/" -reports "0, 1, 5, 7" -zip "./PS_Qex_MDV3_output/PS_Qex_MDV3.zip" -temp_folder "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/Embryo_fractions/Qexactive/FDR_Comparison
/temp/"

I then get this error:
Path configuration completed.
Wed Jan 20 16:23:03 GMT 2016 Unzipping test.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Wed Jan 20 16:25:18 GMT 2016 An error occurred while creating the PeptideShaker project.
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:635)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:203)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Wed Jan 20 16:25:18 GMT 2016 Project successfully created.
Wed Jan 20 16:25:18 GMT 2016 Saving results.
Wed Jan 20 16:25:18 GMT 2016 An exception occurred while saving the project.
java.lang.NullPointerException
	at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:311)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:227)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Wed Jan 20 16:25:18 GMT 2016 Starting report export.
Wed Jan 20 16:25:18 GMT 2016 An error occurred while exporting the Certificate of Analysis.
java.lang.NullPointerException
	at com.compomics.util.Util.getFileName(Util.java:188)
	at eu.isas.peptideshaker.export.sections.PsSearchParametersSection.writeSection(PsSearchParametersSection.java:97)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:310)
	at eu.isas.peptideshaker.cmd.CLIMethods.exportReport(CLIMethods.java:296)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:324)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Wed Jan 20 16:25:18 GMT 2016 An error occurred while exporting the Default Hierarchical Report.
java.lang.NullPointerException
	at eu.isas.peptideshaker.export.sections.PsProteinSection.writeSection(PsProteinSection.java:145)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:298)
	at eu.isas.peptideshaker.cmd.CLIMethods.exportReport(CLIMethods.java:296)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:324)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Wed Jan 20 16:25:18 GMT 2016 An error occurred while exporting the Default Peptide Report.
java.lang.NullPointerException
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:128)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:292)
	at eu.isas.peptideshaker.cmd.CLIMethods.exportReport(CLIMethods.java:296)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:324)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Wed Jan 20 16:25:18 GMT 2016 An error occurred while exporting the Default Protein Report.
java.lang.NullPointerException
	at eu.isas.peptideshaker.export.sections.PsProteinSection.writeSection(PsProteinSection.java:145)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:298)
	at eu.isas.peptideshaker.cmd.CLIMethods.exportReport(CLIMethods.java:296)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:324)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)

Wed Jan 20 16:25:18 GMT 2016 Zipping project.
Wed Jan 20 16:25:18 GMT 2016 PeptideShaker processing failed. See the PeptideShaker log for details.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:361)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)

Any help greatly appreciated.

Craig

**Comment by cdlawless** [comment]
One of the issues I have noticed is the parameter is being zipped up without the .par extension. When I try importing the zip file to the PeptideShaker GUI this does not get populated.

**Comment by hbarsnes** [comment]
Hi Craig,

The first line where it complains is due to the FASTA file not being set in the parameter file? Is this possible? How did you create the parameter file, via the GUI or on the command line? Maybe you can open the parameter file in a text editor and check if the "fastaFile" option is set or not?

> One of the issues I have noticed is the parameter is being zipped up without the .par extension. When I try importing the zip file to the PeptideShaker GUI this does not get populated. 

I would guess that it ends up with the same FASTA file error and therefore cannot load it. But that we can check if you look in the PeptideShaker log file?

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

I created the parameter file via the command line too:
java -Xms1024M -Xmx4096M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.4.1/SearchGUI-2.4.1.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out Qex_MDV3.par -fixed_mods "Carbamidomethylation of C" -variable_mods "Oxidation of M, Acetylation of protein N-term" -db /mnt/fls01-home01/mjfidcl2/scratch/DDIP/Vanilla/slola_proteome_vanilla_v1_concatenated_target_decoy.fasta -prec_tol 10 -frag_tol 0.5 -enzyme "Trypsin" -mc 2

**Comment by hbarsnes** [comment]
Ok, looks ok to me. And the FASTA file clearly seems to be set. Did you check the PeptideShaker log when loading the parameter file in the GUI?

**Comment by hbarsnes** [comment]
Just tested the similar command lines and I also get the problem with the parameter file missing it's .par ending. I'll look into it and get back to you.

**Comment by hbarsnes** [comment]
The problem seems to be the way in which we look for the parameters file when processing the input to SearchGUI. We will get it fixed in the next release which is hopefully coming out at the end of this week.

In the meantime there is a dirty workaround that seems to work. Just add "-out /mnt/lustre/scratch/mjf
 idcl2/DDIP/Embryo_fractions/Qexactive/FDR_Comparison/Qex_MDV3.par" to your command line, i.e. repeat the content of the "-id_params" option but with the "-out" option (and keep the "-id_params" option as before). This tricks the code into picking up the correct parameter file. A hack, but at least this should make it possible for you to process your data while waiting for the new version.

**Comment by hbarsnes** [comment]
The issue should have been fixed with the release of SearchGUI 2.5.0 (and PeptideShaker 1.5.0). If not, please let us know and we'll reopen the issue.
