### ISSUE TITLE
NullPointerException when requesting list of all available mods.

### ISSUE THREAD

**Issue by slurmclassic** [compomics/searchgui#91]
When using the command line, requesting the list of all available mods using the '-mods' switch of 'IdentificationParametersCLI' gives an exception in compomics:

```
c:\Users\SPerkins\Downloads\SearchGUI-2.6.4-windows\SearchGUI-2.6.4>java -Djava.awt.headless=true -cp SearchGUI-2.6.4.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -mods
java.lang.NullPointerException
        at com.compomics.util.experiment.identification.parameters_cli.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:1368)
        at com.compomics.util.experiment.identification.parameters_cli.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:115)
        at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.initite(AbstractIdentificationParametersCli.java:92)

        at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)
```

**Comment by hbarsnes** [comment]
Hi.

Thanks for telling us about this. It will be corrected in the next release. In the meantime you can get around the problem by adding the "-out" option to the command line. The parameter file will not be created, but this will allow you to list the modifications.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi,

This issue has been fixed in the latest releases of the tools.

Best regards,
Harald
