### ISSUE TITLE
IdentificationParametersCLI -prec_ppm issue

### ISSUE THREAD

**Issue by norazrin** [compomics/searchgui#97]
Hi 

I'm trying to set the -prec_ppm option to Da using -prec_ppm by setting it to 0 as per the IdentificationParametersCLI documentation. However, I get the following error:

Error parsing the prec_ppm option: Found 0. Supported input: [1, 2].

If I set -prec_ppm to 2 I get the following error:
java.lang.IllegalArgumentException: Incorrect value for parameter prec_ppm: 2. 0 or 1 expected.
	at com.compomics.util.experiment.identification.parameters_cli.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:149)
	at com.compomics.util.experiment.identification.parameters_cli.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:115)
	at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:92)
	at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
	at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)

I'm using IdentificationParameters via SearchGUI 2.7.1 

Any idea what is going on? I need to set my MS1 tolerance to 0.2Da.

Kind Regards

Azrin

**Comment by hbarsnes** [comment]
Hi Azrin,

Thanks for telling us about this. Clearly a bug in our code. The value is now requested as either 0 or 1, where 0 means Da and 1 ppm, default is ppm. If you update to the just released version of SearchGUI the error should go away. Please let us know if this is not the case and we'll reopen the issue.

Best regards,
Harald
